### ISSUE TITLE
Wrong count of Github issues, when logged in.

### ISSUE THREAD

**Issue by tushar-chauhan** [npm/newww#1002]
The website shows wrong count for github issues when I am logged into my npmjs account. The count is correct when not logged in.

**Comment by icyflame** [comment]
@tushar-chauhan 
Please make the following clarifications:

1. Which website are you talking about? (I presume you are talking about a package page?) please share the **URL** and screenshot of the page that you are referring to. Also, share the GitHub URL of whatever package you are talking about.

2. Is this issue universal? Does it occur on all your packages, or just one particular package?

**Comment by tushar-chauhan** [comment]
@icyflame
This issue is now gone. I see the github issue counts are same whether I am logged in or not.
I have an npm module [loopback-connector-sqlite](https://www.npmjs.com/package/loopback-connector-sqlite) connected to this [Github Repo](https://github.com/Synerzip/loopback-connector-sqlite), It always used to show 1 github issue count, even though there were no issues on Github. This used to happen when I used to be logged onto the npmjs website.
