### ISSUE TITLE
`-g` flag is no longer shown for packages that prefer global installation

### ISSUE THREAD

**Issue by mklement0** [npm/newww#1017]
This seems to be a regression bug: see #133

**Comment by zeke** [comment]
It's an issue in the new registry. The new private API that the website consumes is not including the `preferGlobal` property in its response object.

**Comment by adambuczynski** [comment]
+1

**Comment by mklement0** [comment]
@adambuczynski: good find; looks like it; @zeke: who should be notified of this private API issue and how, and who can/should do it?

**Comment by flesler** [comment]
+1

**Comment by aredridel** [comment]
Closing as a duplicate of #960
