### ISSUE TITLE
Markdown: If no empty line follows an HTML comment, the following paragraph is rendered literally

### ISSUE THREAD

**Issue by mklement0** [npm/newww#1018]
**If _no empty line_ follows an HTML comment in the Markdown source of a package's read-me file, the following paragraph is rendered _literally_** - no Markdown processing takes place.

An example of this problem can be seen in the TOC title at https://www.npmjs.com/package/doctoc.

Here's a snippet that reproduces it (as of markdown-it 4.2.1):
	
	> console.log(require('markdown-it')({html: true}).render("\n*a*\n*b*"))	
	
	*a*
	*b*
	
Inserting another `\n` after the comment makes the problem go away.

	> console.log(require('markdown-it')({html: true}).render("\n\n*a*\n*b*"))
	
	<p><em>a</em>
	<em>b</em></p>

**Comment by aredridel** [comment]
This is related to #1627 and awaiting that decision
