### ISSUE TITLE
README.md not updating for package node-9gag

### ISSUE THREAD

**Issue by sachinB94** [npm/newww#1022]
npmjs.com shows old version of the README.md for package 'node-9gag'. Its been 2 days, the README is still not updated, though downloading the package gives the correct README.

**Comment by samuelcouch** [comment]
Have you tried bumping the patch version?

**Comment by icyflame** [comment]
@samuelcouch 

He seems to have already done that. ([check this diff](https://github.com/sachinB94/node-9gag/commit/be6f6f04972f9787b6b3c756bfe1f298bd4875b3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L3) )

@sachinB94 By the README not being updated, do you mean the `access` section not being visible on the NPM page, [here](https://www.npmjs.com/package/node-9gag) ?

**Comment by sachinB94** [comment]
By the README not being updated, I meant that the README show is of version 0.1.0. The latest README which needs to displayed must be the one shown here https://github.com/sachinB94/node-9gag

**Comment by soldair** [comment]
i see the old readme in couch on npm. if you could run another npm publish it would be great to know the result.
your npm and node version could be of help too.

**Comment by sachinB94** [comment]
I bumped the version to 0.2.2, still no change.

node v0.12.4
npm v2.11.0

**Comment by icyflame** [comment]
@sachinB94 Got it!

You have defined your readme here: https://github.com/sachinB94/node-9gag/blob/master/package.json#L30

Remove that, and then do :- 

```
npm version 0.2.3
npm publish
```

And then you should be alright!

Find a working copy of the code [on github here](https://github.com/icyflame/node-9gag)
And the published package with updated readme [on NPM here](https://www.npmjs.com/package/@icyflame/node-9gag)

P.S. The lines 30 through 36 are not required at all. You can let homepage be there, but you can remove everything else. IMHO that part is absolutely unnecessary.

**Comment by soldair** [comment]
great find @icyflame ill close this. reopen if you still have issues @sachinB94
