### ISSUE TITLE
fix typeahead search

### ISSUE THREAD

**Issue by zeke** [npm/newww#103]
This is not working with browserify:
```js
require('npm-typeahead')({
  npmUrl: '',// URL to re-direct the user to.
  searchUrl: 'https://typeahead.npmjs.com', // URL for search npm-typeahead REST server.
  $: $ // jQuery dependency.
});
```

even this breaks:

```js
require('npm-typeahead')
```

throwing

```
Uncaught TypeError: Cannot read property 'isArray' of undefined index.js:10792
```

in the browser.

**Comment by zeke** [comment]
Hey @bcoe I guess nobody misses typeahead search. At least no one has said anything since December 9th...

**Comment by bcoe** [comment]
alas, I think this is true. Let's revisit it when we can make revamping
search a high priority.
