### ISSUE TITLE
Broken github-links

### ISSUE THREAD

**Issue by nknapp** [npm/newww#1044]
I occasionally find interesting packages of which I'd like to inspect the source code. I click on the github link and get a "404 This is not the page you are looking for".
It would be great if `npmjs.com` told me that before, so I didn't have to click the link

Other measures I could imagine, but I am not sure if it's morally wanted:
* Notifiy the owners of the package when the github page does not exist anymore. Maybe they forgot to change the url in the `package.json`.
* Provide a lower rank for those packages in the search on `npmjs.com`. This might look like a punishment for the owner, but I think of it more as a quality-measure for the package. I usually want have at least a short look at the github-repo, to look at the source or to see if there is more documentation than the README.md. Ranking repos down would mean that I first get packages where I can do that.

Finding out about the broken link could be done when someone is watching the package on npm. You already look for open issues, so it should not be too hard to check whether the repo exists or not.
If it doesn't you could also store the information and notify the owner.

**Comment by aredridel** [comment]
What sort of links are these? Is it related to #1418, in that links that have only relative paths don't go where expected?

**Comment by aredridel** [comment]
No response, closing.

**Comment by nknapp** [comment]
I looked for the modules I meant and didn't find them again. Will post here when I have concrete examples. I think they were links to the issues page of the project
