### ISSUE TITLE
Certificate issues trying to develop locally

### ISSUE THREAD

**Issue by sobering** [npm/newww#1045]
I've been trying to get the `newww` app running locally but am running into certificate issues. Running `npm run dev` fires up the server successfully. When navigating to the app in my browser, I get a certificate warning from Chrome (expected?), but when I click "proceed anyway", the app spits some certificate errors into the console and I'm stuck.

```
2015-06-18T16:49:12.747Z error EXTERNAL: {
  "time": "2015-06-18T16:49:12.747Z",
  "hostname": "beavis",
  "pid": 5659,
  "level": "error",
  "name": "EXTERNAL"
}
2015-06-18T16:49:12.747Z error EXTERNAL: Error: self signed certificate
  at Error (native)
  at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
  at TLSSocket.emit (events.js:104:17)
  at TLSSocket._finishInit (_tls_wrap.js:460:8)
```

Any help is appreciated, I'd love to be able to contribute.

**Comment by alrra** [comment]
@sobering See: #761.

**Comment by sobering** [comment]
Wow, sorry! I completely missed that line in the README. I'll be more diligent next time!

**Comment by samuelcouch** [comment]
@sobering curious what line you missed that fixed the problem?
