### ISSUE TITLE
Pushing a package results in {"error":"unexpected status code: 404"}

### ISSUE THREAD

**Issue by maartenba** [npm/newww#1062]
Pushing a package to npmjs.org results in an error 500 beign returned, with `{"error":"unexpected status code: 404"}` as the body.

I'm not using the npm client directly, I am using the registry client lib (https://github.com/npm/npm-registry-client) with a minor modification that does basic authentication instead of using a token. Reason is I want this to run from a CI server.

If it helps, the package name is "jquery.dirtyforms.helpers.alwaysdirty". Looks like a valid pacage name to me?

**Comment by maartenba** [comment]
Seems to be related to using a non-existing username. Would be great to have a nicer error message there :-)

**Comment by soldair** [comment]
sounds like this is resolved. ill close it but if you still have an issue reopen it please

**Comment by maartenba** [comment]
Yeah this one is fixed.
