### ISSUE TITLE
Exact match searches don't show up first in the results

### ISSUE THREAD

**Issue by polson136** [npm/newww#1066]
When searching for a specific package, say "sequelize", the "sequelize" package does not show up in the first page of results. Granted, you could select it from the drop down box, but if you are fast at typing, it is possible to enter your query before the drop down appears, therefore it should not be a substitute for the search results. The exact match should be either at the top of the result list or represented in some other way.

**Comment by flyswatter** [comment]
Yeah, I found the same is true for many other search queries, like "tape", where I searched the first 12 pages of results to not find the module whose name was an exact match!

**Comment by zhanzhenzhen** [comment]
When typing "bluebird" the famous bluebird package is even at the second page. This is weird...

**Comment by rreusser** [comment]
Are +1's useful or just irritating?

Only wanted to register that this really seems to affect discoverability. As a stopgap, even just sort options (downloads, dependent count, stars, ?) would be extremely helpful.

'bluebird' is the first result in the dropdown if you type 'bluebird', but as a random counterexample to the dropdown's usefulness, 'euclideanmst' doesn't return a module with the exact name.

**Comment by rreusser** [comment]
Looks great! Much appreciated.

**Comment by zhanzhenzhen** [comment]
Looks like name with a dash such as "coffee-script" still has this problem.

**Comment by jefflembeck** [comment]
@zhanzhenzhen Thanks! This is a known issue and there is a bug filed for it - https://github.com/npm/newww/issues/1103. We're iterating and making the search better piece by piece.

**Comment by zhanzhenzhen** [comment]
This bug has been fixed. But now I've found an exception:
Type "proof".
The exact match is only at the second position.

**Comment by focusaurus** [comment]
I have found another exception today, `joi`. Has this regressed?

**Comment by flyswatter** [comment]
I also think this has regressed in some way. For example, [bluebird](https://www.npmjs.com/search?q=bluebird) is again not returned first for an exact query.

**Comment by evanjbowling** [comment]
I just noticed this as recent as April 16. I was searching for "socket.io" and it came up with different results.

Reproduce by opening: https://www.npmjs.com/search?q=socket.io
Observation: It returns either "socket.io" or "socket.io-zeromq" first.

Possible related issues I found: #1103, #1096, #1630 
While this isn't ideal, it didn't really prevent me from finding the right package.

**Comment by flyswatter** [comment]
@rockbot this should be reopened.
