### ISSUE TITLE
Private modules notification size

### ISSUE THREAD

**Issue by andrewmcwatters** [npm/newww#1094]
NPM's new site is great, and the private modules service is an excellent addition! However, please consider decreasing the size of the private modules notification, moving it, or somehow generally making it much less prominent.

Making this element take up such a large portion of viewport real estate is not going to directly encourage more sales, and only makes using the site much more irritating each time it needs to be dismissed before proceeding onto the site.

I'm not sure where the inspiration for essentially pushing content entirely out of visibility comes from, but this isn't a good browsing experience.

**Comment by andrewmcwatters** [comment]
Closed due to no response in 2 weeks.

**Comment by jefflembeck** [comment]
@andrewmcwatters Sorry about the slow response time! We hear you loud and clear and totally agree with you on the issue. We're looking into doing some design work that will affect this in the near future. Thanks!

**Comment by andrewmcwatters** [comment]
It's all good, @jefflembeck. You folks are a busy bunch, and I figured this was just a low-priority, or non-issue.

Have a great weekend!
