### ISSUE TITLE
Redis Subscription doesnt work with test browser (Mocha) 

### ISSUE THREAD

**Issue by pratikfromaspire** [npm/newww#1097]
fs.syncExists method results "undefined" from binding.js when try to use is with gulp test-browser of task Mocha.js.

All the methods of fs module is not available using gulp test-browser.

We are using Node.js 0.12.7

here is the git link for your reference. https://github.com/aspiresoftware/translation-manager-client-app

We are in urgent need of solution. Quick inputs would be of great help.

**Comment by KenanY** [comment]
@pratikfromaspire Sorry, how is this issue relevant to this repository?

**Comment by KenanY** [comment]
@pratikfromaspire ping?

**Comment by aredridel** [comment]
No response. Closing.
