### ISSUE TITLE
Large images overflow package readme

### ISSUE THREAD

**Issue by btmills** [npm/newww#1104]
For example, the readme for the [babel package](https://www.npmjs.com/package/babylon) (screenshot below) includes a large png image that overflows its container. When this happens, it (transparently) covers the sidebar, making those links unclickable. I was able to fix this temporarily in the browser dev tools by setting `max-width: 100%;` on the offending `<img>`.

![screenshot 2015-07-21 12 42 40](https://cloud.githubusercontent.com/assets/1709537/8806705/f1ef0b98-2fa5-11e5-9200-377246467b6e.png)

**Comment by jefflembeck** [comment]
We should likely switch to using `max-width: 100%` on all `img` tags, instead of just ones that are in markdown.

This will take some testing.

**Comment by aredridel** [comment]
This has been fixed AFAIK. Feel free to ping us if this doesn't resolve it completely for you.
