### ISSUE TITLE
Add 'Remember me' login option

### ISSUE THREAD

**Issue by facekapow** [npm/newww#1105]
You know how when you login to Github, it remembers you logged in, even if you close the tab or even the browser? Yeah, npm needs that. It's annoying having to login every time I clean up my tab mess and accidentally delete the npmjs tab. It's not life-threatening, but it's a problem you eventually notice. Plus, it's easy to implement, a simple little cookie is all you need.

**Comment by vkbansal** [comment]
+1 for this feature.

**Comment by facekapow** [comment]
Closing this as I've noticed it's been implemented in the npm website. :+1:
