### ISSUE TITLE
width and height attributes filtered from img tags

### ISSUE THREAD

**Issue by rreusser** [npm/newww#1107]
I'm trying to add equations to readmes as retina PNGs. newww permits img tags but filters the `width` and `height` attributes, preventing retina scaling.

Examples:
- https://www.npmjs.com/package/gulp-markdown-equations vs. https://github.com/rreusser/gulp-markdown-equations
- https://www.npmjs.com/package/ndarray-blas-level1 vs. https://github.com/scijs/ndarray-blas-level1
- https://www.npmjs.com/package/fly vs. https://github.com/flyjs/fly

At the moment, I'm inclined to just leave it as is and assume people will navigate to github if it looks wonky.

Useful attributes that are also excluded:
- `valign` for `<img>` tags
- `align` for `<p>` tags

Other max-width related issues that don't quite cover this:
- npm/newww#1104
- npm/newww#1060
- npm/newww#94

Alternate solution:
- Use SVG. Problem: github forbids SVGs on the github domain (i.e. simple relative paths; for [security reasons that are totally unclear](https://github.com/isaacs/github/issues/316)) and proxies images to camo.githubusercontent.com, making it tricky to automate the process.

**Comment by rreusser** [comment]
Ah, there it is. It's explicitly not allowed. Here's the line of code: https://github.com/npm/marky-markdown/blob/master/lib/sanitize.js#L47

**Comment by rreusser** [comment]
Pull request filed. We'll see.

**Comment by aredridel** [comment]
Looks like this was merged and should be resolved. Can you let us know if what we've done does not suffice?

**Comment by rreusser** [comment]
Looks great! Thanks so much!
