### ISSUE TITLE
HTTPS mixed content issue

### ISSUE THREAD

**Issue by polybuildr** [npm/newww#1110]
Currently, when accessing the site, say https://www.npmjs.com/package/gulp-minify-css, my browser shows a warning about the connection, pointing out that some resources are still being served using HTTP, thus making certain kinds of MITM attacks possible.

**Comment by KenanY** [comment]
Worth noting that this is because of the `shields.io` "npm version" badge on that package's README.

**Comment by KenanY** [comment]
@polybuildr ping, does my explanation make sense to you? [This badge](http://img.shields.io/npm/v/gulp-minify-css.svg) is being served over HTTP, hence the warning. This should be fixed on the package's end...

**Comment by polybuildr** [comment]
Yeah, it does. Maybe it should be looked into anyway, but certainly an issue on the package's end.
