### ISSUE TITLE
Old README version

### ISSUE THREAD

**Issue by celsomarques** [npm/newww#1111]
Hi folks,

I publish a package yesterday but when I open the link after a search it shows the old README.
How can I fix that?

And today I included the repository url in package.json, how can I update this info here?

The package is: datepicker-for-ionic.

Thank you in advance.

**Comment by alrra** [comment]
@celsomarques It seems that `npm` fetches the state of your project as it was at https://github.com/celsomarques/ionic-datepicker/commit/fd77df549e48583ea18d34886cd487225b803a01 [:paperclip:](https://cloud.githubusercontent.com/assets/1223565/8888236/ff2e7bd0-32ad-11e5-8107-a172ac220fe5.png)

Try releasing a new version (e.g.: `v1.0.1`) and publish it on `npm`.

**Comment by celsomarques** [comment]
It worked!
Thx a lot!
