### ISSUE TITLE
Long headings are truncated rather than line-wrapped

### ISSUE THREAD

**Issue by mklement0** [npm/newww#1114]
GitHub simply line-wraps headings that get too long; e.g.:

https://github.com/mklement0/voices#osx-service-for-speaking-selected-text-with-a-specific-voice

By contrast, npmjs.com truncates the same text with an ellipsis `...`:

https://www.npmjs.com/package/voices#osx-service-for-speaking-selected-text-with-a-specific-voice

Showing the full heading, even if it means requiring display of more than 1 line, strikes me as the better choice.

**Comment by ncawthon** [comment]
Nice references - agree with your points on how to address text-overflow.

**Comment by alrra** [comment]
Note: I've open a pull request to change this (see: https://github.com/npm/newww/pull/1119).

**Comment by mklement0** [comment]
@ncawthon: thanks; glad to hear it; @alrra: great, thanks.
