### ISSUE TITLE
wombat private modules banner not closing

### ISSUE THREAD

**Issue by doowb** [npm/newww#1123]
I was logged out and the banner was showing. When I logged in the banner was still there and I tried to click "Close" and "Not thanks" and nothing happens.

I'm on Chrome Version 44.0.2403.125 (64-bit)
OSX Version 10.9.5

**Comment by jefflembeck** [comment]
@doowb 

Any chance you can do a hard refresh on the page for me?

I think this might be a caching issue. If so, I'm in the works to fix that potential problem asap.

**Comment by doowb** [comment]
Hard refresh worked now, thanks.
