### ISSUE TITLE
A @tjholowaychuk package is badly served by npm, this is recent

### ISSUE THREAD

**Issue by Yvem** [npm/newww#1127]
TJ npm packet "sass" https://www.npmjs.com/package/sass is no longer correctly served, it displays a virtual "Error" packet at this url. It is no longer installable via npm.

![sass error](https://cloud.githubusercontent.com/assets/481983/9085812/71c3fe7e-3b80-11e5-8879-f39d11891d44.png)

The package exists, it is listed here :
https://www.npmjs.com/~tjholowaychuk

This is breaking our production deployments.

**Comment by chpill** [comment]
This is causing our `npm install` to fail... Is this an issue with npm or with the package itself?

**Comment by Yvem** [comment]
The package still appears on third-party sites : https://libraries.io/npm/sass

**Comment by samccone** [comment]
https://twitter.com/samccone/status/628914963139141632

Same issue with http://npmjs.com/package/strscan

cc @linclark

**Comment by bstst** [comment]
Same here. Help!

**Comment by Yvem** [comment]
@all let's +1 to a similar issue in the npm repo itself : https://github.com/npm/npm/issues/9178

**Comment by Yvem** [comment]
pb réglé : https://github.com/npm/npm/issues/9168#issuecomment-128034802
