### ISSUE TITLE
install command on top right of package page can be confusing

### ISSUE THREAD

**Issue by ehsalazar** [npm/newww#1179]
We've received a few support inquiries concerning the command on the top right of the package profile page. 

Some new users believe:
- If they click the icon and command, they'll be able to download the package via the website.
- Since it isn't clickable, they fear there's an issue with their account.

Perhaps a different icon could be used? I've included a screenshot for reference. 

![download](https://cloud.githubusercontent.com/assets/7298179/9395829/be1efffa-4745-11e5-90fb-3a5f015b4680.png)

**Comment by zeke** [comment]
A few ideas:

1. Make the icon into a [zeroclipboard](https://www.npmjs.com/package/zeroclipboard) link that copies the install command to the clipboard. Maybe some kind of feedback saying "Copied to clipboard" would help.
1. Make the icon into a link that toggles open a little notification that says, "To download this package, install [node.js] and run `npm install foo` from your command line".. or something along those lines.

**Comment by aredridel** [comment]
These are some great ideas!

Our current plan resembles point 1, which is actually issue #1120 -- so I'm going to close this issue.
