### ISSUE TITLE
Talk about error placement and handling strategy, regarding user messaging

### ISSUE THREAD

**Issue by aredridel** [npm/newww#1226]

**Comment by aredridel** [comment]
@ncawthon We've got a couple of different ad hoc approaches to handling errors, for many cases:

* form level user validation errors that the user must take action on to complete what they were doing
* global notices of account status and information
* process errors where something went wrong and we're telling the user even though they can't act other than to retry

**Comment by ncawthon** [comment]
in an ideal world...

   - form level would be done in-line, so that I might be made aware of
   which inputs are errant.

   - global notices of account and / or system status should be made aware
   of which users have confirmed seeing (and dismissing this). I would think
   this would also be targetable to users with certain access / settings. You
   might also find this to be an announcement platform for feature
   improvements and non-operational messaging.

   - process errors is a great edge-case. I think the importance here (for
   errors) is to log when/why this occurs, for our own benefit. I'd also
   include confirmations of successful processes to this one, similar to a
   flash notification.


On Fri, Aug 28, 2015 at 11:26 AM, Aria Stewart <notifications@github.com>
wrote:

> @ncawthon <https://github.com/ncawthon> We've got a couple of different
> ad hoc approaches to handling errors, for many cases:
>
>    - form level user validation errors that the user must take action on
>    to complete what they were doing
>    - global notices of account status and information
>    - process errors where something went wrong and we're telling the user
>    even though they can't act other than to retry
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/newww/issues/1226#issuecomment-135853989>.
>



-- 
nc

Nick Cawthon
gaugedesign.com
510 542 7364

**Comment by ncawthon** [comment]
![image](https://cloud.githubusercontent.com/assets/351221/9585755/9aa00e8a-4fcd-11e5-94a3-8b122201492a.png)

system-wide-targeted announcement

![image](https://cloud.githubusercontent.com/assets/351221/9585770/b77e889c-4fcd-11e5-895c-7db0df921162.png)

system-wide-targeted announcement mobile

**Comment by ncawthon** [comment]
![image](https://cloud.githubusercontent.com/assets/351221/9585782/c62ef43a-4fcd-11e5-916d-0513a9fca3f2.png)

dismissible notification

![image](https://cloud.githubusercontent.com/assets/351221/9585793/da6b9fe8-4fcd-11e5-8e6f-b61ffde6b97e.png)


dismissible notification mobile

**Comment by ncawthon** [comment]
![image](https://cloud.githubusercontent.com/assets/351221/9585815/f606c2f0-4fcd-11e5-939d-ce08d53e85b0.png)

flash notification

![image](https://cloud.githubusercontent.com/assets/351221/9585822/05691324-4fce-11e5-83ee-59eaf071ecd1.png)

flash notification mobile

**Comment by ncawthon** [comment]
![image](https://cloud.githubusercontent.com/assets/351221/9585845/23d3fbbc-4fce-11e5-821e-5db1d02b9a65.png)

flash notification - success

![image](https://cloud.githubusercontent.com/assets/351221/9585853/31927602-4fce-11e5-86c3-7127c108e7ba.png)

flash notification - mobile

**Comment by aredridel** [comment]
Hmm. No interaction on a flash?

**Comment by ncawthon** [comment]
nope - dismissible t'would, but flash notification is meant for a three-second pause or so... most likely implementation would be form submission.

**Comment by aredridel** [comment]
Wow. With both my use pattern and if someone is a slow reader or on a screen reader or other assistive device, that would be really un-fun. (I open pages in new tabs, or switch tasks if there's even a hint of slowness.)

**Comment by ncawthon** [comment]
Good point. If there is ever anything that we need the user to read, we should classify it as dismissible. I think you mentioned 'system wonky, something didn't work' as an example. However, success notifications are pretty temporal and could be relegated to the sole implementation for flash notifications. Thoughts?

**Comment by aredridel** [comment]
I think if one wants the reader to read something, it should probably stay put while they do so. If you don't need to tell them, then don't.

**Comment by ncawthon** [comment]
yar - ok. kill the flashes altogeher. the user would likely see the effect of their process anyway. perhaps there's a state change in whatever element that (might) be.  color-shift / transition, or something similar.

**Comment by ncawthon** [comment]
![image](https://cloud.githubusercontent.com/assets/351221/9587271/80634a10-4fd6-11e5-9d74-0230a3430741.png)

entity added successfully (color shift)

![image](https://cloud.githubusercontent.com/assets/351221/9587290/976d93dc-4fd6-11e5-998c-ac756e0f4f5b.png)

mobile

**Comment by ncawthon** [comment]
...if we're still gun-shy about transitions to portray process (due to context switching), I'm fine with holding the above state changes until the next page load. Just temporarily having the color shift to function as an indicator of successful process.

**Comment by aredridel** [comment]
gun-shy? (I'm not sure I have the context for your last comment.)

**Comment by ncawthon** [comment]
sry - if we're still a bit wary of...

**Comment by ncawthon** [comment]
(as I am with guns)

**Comment by aredridel** [comment]
Ah. I don't know that we're wary, we just don't have many in-page actions. The whole site is very web 1.0 and works well that way. Most transitions are in fact a page load.
