### ISSUE TITLE
allow for license to be blank?

### ISSUE THREAD

**Issue by ncawthon** [npm/newww#1241]
Observed user behavior of putting in MIT for the license field because it was required, then manually removing it immediately after the package.json was created. Reason being, this user was creating a package for just his team to work on and did not feel that they fell under any category of licensing. 

Not sure of the impact of orgs / enterprise on the input of license within the above mentioned scenario.

**Comment by aredridel** [comment]
The value `"UNLICENSED"` is just for this case.

**Comment by ncawthon** [comment]
thx!

**Comment by danmactough** [comment]
> The value "UNLICENSED" is just for this case.

When I try this using `npm@2.11.3/node@0.12.7` I get the following unexpected response:

```
...
license: (ISC) UNLICENSED
Sorry, license should be a valid SPDX license expression and license is similar to the valid expression "Unlicense".
...
```

Bonus confusion points because the [Unlicense](http://unlicense.org/) is **QUITE** different from Unlicensed. :smile: 

But I'm guessing it's an "old" npm version.
