### ISSUE TITLE
Orgs: Link to create an org is broken

### ISSUE THREAD

**Issue by aredridel** [npm/newww#1257]
via @seldo: Also: after you verify your email address, the page links to "create an org" but the link is broken (/orgs instead of /org I think)

**Comment by aredridel** [comment]
@seldo: I can't replicate this -- this was a non-org user without a validated email address? Logged in to start?

**Comment by aredridel** [comment]
This is probably fixed by #1258 too.

**Comment by mstade** [comment]
I tried following the link, and had forgotten my password. I reset it, followed the link again, and was redirected to my profile page. I made sure my email was verified, but this changed nothing. The [org link][1] just keeps redirecting to my profile page.

[1]: https://www.npmjs.com/org?join-beta

**Comment by aredridel** [comment]
That is indeed happening for users who aren't eligible for the first round of beta! Investigating why now!
