### ISSUE TITLE
“Edit User” buttons in Users screen of orgs management behaves unexpectedly

### ISSUE THREAD

**Issue by cowperthwait** [npm/newww#1299]
On the `Users` screen of orgs management, clicking the `Edit User` button under the `unpaid` <=> `paid`switch causes the window to refresh and scroll down ~295 pixels. The user expects that clicking this button may lead to a screen for editing user attributes.

**Comment by jefflembeck** [comment]
Closing as duplicate- See: https://github.com/npm/newww/issues/1261
