### ISSUE TITLE
HTML not Escaped in Search Autosuggetion Dropdown

### ISSUE THREAD

**Issue by jalcine** [npm/newww#1300]
I think this is moreso a problem on <Constructor.io> but when you search for a project that makes use of a valid HTML tag, it renders as such in the description field. It also looks like it's escaped by npm.
![snapshot375](https://cloud.githubusercontent.com/assets/452100/9705892/09349432-54a2-11e5-9c68-11840589bb03.png)

**Comment by aredridel** [comment]
Nice catch! 

This is handled by constructor.io, so I'll look at getting them involved.

**Comment by aredridel** [comment]
@EliFinkelshteyn -- this could be important!

**Comment by jalcine** [comment]
[**@aredridel**](https://github.com/aredridel) commented on [Sep 8, 2015, 10:19 AM EDT](https://github.com/npm/newww/issues/1300#issuecomment-138575784 "2015-09-08T14:19:49Z - Replied by Github Comment Enhancer"):
> Nice catch! 
> 
> This is handled by constructor.io, so I'll look at getting them involved.

Thanks!

**Comment by EliFinkelshteyn** [comment]
Thank you both! @danmcc can you have a look? This is dangerous.

**Comment by danmcc** [comment]
Yup!  On it.

**Comment by danmcc** [comment]
All fixed!  Thanks @jalcine!

**Comment by aredridel** [comment]
Seconded! Thank you very much, @jalcine

**Comment by jalcine** [comment]
Thank you guys for handling this :+1:

**Comment by aredridel** [comment]
Yay!
