### ISSUE TITLE
Markdown not parsed properly from Github's README file

### ISSUE THREAD

**Issue by tushar-chauhan** [npm/newww#1304]
Hi,

I have this [Github repository](https://github.com/Synerzip/loopback-connector-sqlite), which holds the codebase for this [Node package](https://www.npmjs.com/package/loopback-connector-sqlite).
If you check the `file_name` parameter description in the **Installation** section on the Github and the npmjs page of it, then you can see the difference in how the markdown's Italics style is being handled in the npmjs website. I guess the markdown parsing for italics has some issue on the website. I am using underscore for italics in markdown.
Please let me know if I am doing something wrong, so that I can correct it on my side.

Thanks

**Comment by aredridel** [comment]
Looks like a difference between how https://github.com/npm/marky-markdown and [Github Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/) render. Not sure which one is correct, but the concept of combining italics with somewhat escape-string-like markup is going to be tricky with all but the most rigorous grammars.

(Markdown isn't one of those, sadly)

**Comment by tushar-chauhan** [comment]
@aredridel Thanks for the reply. I have removed the italics from the markdown for consistency of the output. I will close this issue now.
