### ISSUE TITLE
Non-ASCII characters broken

### ISSUE THREAD

**Issue by Flimm** [npm/newww#1319]
Look at this example, under the heading IRI support: https://www.npmjs.com/package/uri-js#iri-support

![Screenshot with mojibake](https://cloud.githubusercontent.com/assets/355454/9821267/29c13184-58b1-11e5-81d5-21123d78365f.png)

If you look at the same README page on GitHub, you can see that it renders correctly there:

![Screenshot without mojibake](https://cloud.githubusercontent.com/assets/355454/9821268/29c3cb2e-58b1-11e5-9455-a2ef7ce3f93f.png)

**Comment by aredridel** [comment]
It looks like that package has invalid UTF-8 in its readme, and github must be doing some funky fallback logic to try a latin-1 character set, or doing guesswork to detect encodings. npm isn't doing that currently (and it's hard to do well without culturally loaded assumptions.)

**Comment by Flimm** [comment]
You're right, it's not UTF-8 it's Latin1. I'll file an issue in that repo. The nice thing about UTF-8 is that there are byte sequences that are invalid, and latin-1 is a pretty sensible fallback in that case.

**Comment by aredridel** [comment]
Yeah. Sensible if you don't mind being eurocentric.

**Comment by Flimm** [comment]
For this particular example [my pull request](https://github.com/garycourt/uri-js/pull/9) was fixed, so I presume the example I gave originally will eventually fix itself.

**Comment by aredridel** [comment]
Yeah. I think we might want to close this as it's mostly a difference in how to handle ambiguous cases given a global default of UTF-8, and not wrong per se.
