### ISSUE TITLE
[docs:scripts] Reference to node-waf

### ISSUE THREAD

**Issue by ronkorving** [npm/newww#1323]
This *has* to be some overlooked legacy, right? See: https://docs.npmjs.com/misc/scripts

**Comment by aredridel** [comment]
Sure is! this is actually a bug in https://github.com/npm/npm not the website -- the docs are generated from its repo.

**Comment by ronkorving** [comment]
Darnit, so this is the 2nd wrong repo I hit with this? :)

**Comment by aredridel** [comment]
Possibly! what was the first?

**Comment by ronkorving** [comment]
The old npm website repo :)

**Comment by aredridel** [comment]
Oh! Hee.

**Comment by aredridel** [comment]
So yeah. I've alerted the CLI team to this issue, but opening one there is probably smart so they can triage it.

**Comment by ronkorving** [comment]
Will do :)
