### ISSUE TITLE
improve display when `license` field altogether missing in registry doc

### ISSUE THREAD

**Issue by othiym23** [npm/newww#1330]
The CLI team would really like everyone to have a valid SPDX clause in their `package.json` file. Until then, this looks a little weird:

<img width="430" alt="2015-09-15 13-34-30 vgnu6" src="https://cloud.githubusercontent.com/assets/418097/9889280/92cb3bc0-5bae-11e5-9ba3-acd991d365a1.png">

I have two suggestions, both of which you're free to ignore:
1. hide the `license` field when there's no license present
2. flip the order, so that it's `license: none` or something similar

I have a certain kind of sympathy for [none license](https://www.youtube.com/watch?v=46kXH6GGtT0), but it does read sort of strangely.

**Comment by KenanY** [comment]
https://github.com/npm/newww/issues/949

**Comment by othiym23** [comment]
Closing as a duplicate of #949, but either way, it would be nice to get this fixed!
