### ISSUE TITLE
README.md file not found, then proceeds to show README.md file

### ISSUE THREAD

**Issue by greduan** [npm/newww#1362]
![screen shot 2015-10-01 at 4 52 53 pm](https://cloud.githubusercontent.com/assets/2314074/10234823/0b5c56a4-685d-11e5-99ce-a997cc98f16f.png)

**Comment by KenanY** [comment]
@greduan The `description` of the package is that error message: https://github.com/crcn/node-auth/blob/3e7340f0fd880337fdbba0b4d68d1169018b2ea6/package.json#L4

**Comment by greduan** [comment]
Well that is misleading... Sorry about this issue. u-u
