### ISSUE TITLE
Jade doesn't appear on packages people 'npm install' a lot

### ISSUE THREAD

**Issue by ForbesLindesay** [npm/newww#1374]
I noticed jade doesn't appear in "packages people 'npm install' a lot" despite reporting much higher numbers of monthly downloads than most packages in that list.  How is that list calculated?

**Comment by aredridel** [comment]
See comment on the linked PR

**Comment by ForbesLindesay** [comment]
I've updated the PR based on that comment.

**Comment by ForbesLindesay** [comment]
So, for the record:

 - You manually choose which package appear in a list titled "packages people 'npm install' a lot" without reference to data on which packages people actually install a lot.  Presumably based on which packages you happen to like?
 - Having manually chosen packages to go in that list, you decided "grunt" was so spectacularly good it should go in that list twice?
 - There is no process for suggesting packages to be added to that list and no visibility into how the list is chosen?

It doesn't seem like npm wants to be seen as trustworthy?

**Comment by seldo** [comment]
@ForbesLindesay: I was the one responsible for putting the list together, so I can tell you how it was generated.

First the problem we were trying to solve: we wanted a list of packages that new users arriving on the home page might want to try out. We didn't want that list to be totally arbitrary, but we were also okay with getting a basic query and then weeding out noise.

We have a large, slow, data-warehouse system we use to do ad-hoc queries of our deep log data. 8 months ago I ran a job that searched logs for packages in "npm install" commands (the client sends a header to the server that includes what command is run, for debugging purposes). This was the list that turned up.

There is a big difference between packages that are _downloaded_ a lot versus packages that are _explicitly_ installed via an "npm install" command. The most-downloaded packages are mostly a pretty boring list -- stuff like `mkdirp`, `q`, `request`, and other packages that are depended upon, one way or another, by nearly every package in the registry. It's not very useful to new users.

The explicitly-installed list, on the other hand, was way more useful. It consists of CLI tools which people directly install a lot -- grunt, gulp, bower -- plus basic webdev packages that people install a lot when first kicking off a project -- hapi, less.

I re-ran the job this morning using a week's data (the original list used a month, which requires a different system and is thus much slower). You can see the raw, unedited results here: https://docs.google.com/a/npmjs.com/spreadsheets/d/120am_J_6g5WKI0ArzoaY3EsYiP_KL1LJrXpVVRoxknY/edit?usp=sharing . I annotated it a bit to explain some of the stranger results. As you can see, jade appears on the list, but not high enough to appear on the home page.

I apologize for our lack of transparency on this, which was entirely the result of doing it in a hurry and then never revisiting it. I hope this helps explain how we got to the list and what we mean by "manual curation".
