### ISSUE TITLE
Same Stat's on different packages.

### ISSUE THREAD

**Issue by am-worx** [npm/newww#1376]
I noticed, that packages stats don't differ, if there is only camel case difference between package names.
Example:
- https://www.npmjs.com/package/jQuery
- https://www.npmjs.com/package/jquery

**Comment by KenanY** [comment]
@am-worx Duplicate of https://github.com/npm/newww/issues/1054?

**Comment by am-worx** [comment]
Yes.

**Comment by jefflembeck** [comment]
Closing as a duplicate of #1054
