### ISSUE TITLE
Markdown: H1-6 tags not parsed correctly

### ISSUE THREAD

**Issue by greduan** [npm/newww#1378]
<img width="1280" alt="screen shot 2015-10-09 at 10 33 17" src="https://cloud.githubusercontent.com/assets/2314074/10398212/5337c96c-6e71-11e5-8b15-a036ad472da9.png">

Dunno if this is intentional or not, but no harm in reporting a bug. :)

**Comment by aredridel** [comment]
We've got a more strict parser than github, so there's a few differences -- this will parse if you use the space after `###` as the commonmark spec shows.

**Comment by greduan** [comment]
All right. If it's part of the standard that's all right. I just expected GitHub to also follow the standard strictly so I assumed something was wrong. Thanks for the quick response. :)

**Comment by aredridel** [comment]
You're welcome!

The standard itself isn't all that standard -- every implementation is a bit of a special snowflake. Commonmark is an attempt to drag 'em together but yeah. They still vaty.
