### ISSUE TITLE
npmjs.com search can serve empty result pages

### ISSUE THREAD

**Issue by essdot** [npm/newww#1390]
I searched npmjs.com for "input mask", and clicked "Next Page" to go to the second page of results. There weren't any results on the page:

<img width="826" alt="screen shot 2015-10-15 at 9 40 32 am" src="https://cloud.githubusercontent.com/assets/3019349/10520879/9a98ef02-7321-11e5-8e9e-a1160c848547.png">

Also, it probably doesn't make a difference, but I noticed that the `q` parameter changed from `input+mask` on the first page to `input%20mask` on the second.

**Comment by aredridel** [comment]
Oh nice catch! Thanks for reporting this!

**Comment by vramana** [comment]
@aredridel Hey, I want to work on this but what should be the expected behaviour on this page?

**Comment by aredridel** [comment]
I'd expect to use the URL form that gives results on all pages, and then page through them neatly -- never showing a blank page unless there are no results at all.

**Comment by aredridel** [comment]
I imagine the bug is just using the wrong url encoding in one spot
