### ISSUE TITLE
Issues with node 4.0/engine specifications needed

### ISSUE THREAD

**Issue by tekd** [npm/newww#1403]
There is a possible bug for node 4.0--when I run it the app crashes. It runs with node 0.12.7. Should engines be specified in the package.json file?

**Comment by aredridel** [comment]
Yes, right now the site requires 0.10 or. 0.12. The oniguruma library needs porting. A PR would be accepted to add an engines spec.

**Comment by taraadiseshan** [comment]
I'm working on a pull request!

**Comment by ashleygwilliams** [comment]
:tada:
