### ISSUE TITLE
Move to node 4!

### ISSUE THREAD

**Issue by aredridel** [npm/newww#1412]
The remaining blocker is getting back to mainline oniguruma

From @soldair: 

> a note about marky-markdown and node 4. we need to go back to marky-markdown from @soldair/marky-markdown and we will be node 4 ready. the main  oniguruma fixed the node 4 issues a while back i have just been slow to go back after i updated marky to be compatible with the latest first-mate

**Comment by aredridel** [comment]
This might be a good thing for @jonathanmarvens to work on too

**Comment by soldair** [comment]
it should "just work" 
to test, replace @soldair/marky-markdown with marky-markdown "^5.4.0"
and make sure readmes still render beautifully

**Comment by ashleygwilliams** [comment]
i didn't realize we weren't using https://github.com/npm/marky-markdown, glad we'll be switching back

**Comment by aredridel** [comment]
Yeah! A bit of a temporary detour while @soldair fixed the memory leak in oniguruma

**Comment by aredridel** [comment]
We have to re-adjust the require-paths as well, not _just_ package.json
