### ISSUE TITLE
Missing publication info on node-sass

### ISSUE THREAD

**Issue by chrisdickinson** [npm/newww#1419]
It looks like node-sass is missing the `"X.Y.Z is the latest of N releases"` bit on the side column (and also the github repo info.)

Attaching a screenshot to make sure it's recorded, this was taken at about `2015-10-21T19:40:00.000Z`.

<img width="1201" alt="screen shot 2015-10-21 at 12 40 44 pm" src="https://cloud.githubusercontent.com/assets/37303/10648053/18e0a002-77f1-11e5-8982-39ad81c31adc.png">

**Comment by soldair** [comment]
fixed. there must have been an issue when importing it into registry relational from the follower
i thought i found an issue with stars but turns out it was just an old version of rr models.
