### ISSUE TITLE
diff / patch syntax highlighting

### ISSUE THREAD

**Issue by dsernst** [npm/newww#1432]
GitHub supports `diff` syntax highlighting:

```diff
old line
old line
+ insert line
old line
- remove line
old line
```

But [npmjs.com](http://npmjs.com) does not. :cry: 

Compare [GitHub](https://github.com/dsernst/npm-run-help) vs [newww](https://www.npmjs.com/package/npm-run-help) for an example.

**Comment by ashleygwilliams** [comment]
hi! this is probably an issue for our markdown parser, [`marky-markdown`](https://github.com/npm/marky-markdown). `marky-markdown` wraps [`markdown-it`](https://github.com/markdown-it/markdown-it).

plz refile an issue on one of those two repos! would love a patch to marky-markdown :)

thanks for contributing! <3
