### ISSUE TITLE
404 links to tonicdev.com 

### ISSUE THREAD

**Issue by jzaefferer** [npm/newww#1446]
For example https://www.npmjs.com/package/qunit links to https://tonicdev.com/npm/qunit which responds with a 404 Not Found. I can't tell how to get that working. It seems like npmjs.com shouldn't link to this so indiscriminately.

**Comment by ashleygwilliams** [comment]
i can/have reproduce(d).

**Comment by ashleygwilliams** [comment]
@jzaefferer does this happen for any other packages? i'm trying to find another and i can't. if you happen to find one that could speed up this debugging process ;)

**Comment by jzaefferer** [comment]
Same issue for https://www.npmjs.com/package/qunitjs -> https://tonicdev.com/npm/qunitjs

**Comment by tolmasky** [comment]
I've looked into it on Tonic's end. I believe its because qunit has a version that is not a valid semver (0.2.0pre). I'm working on having that not break it right now, so I'll report back in a few min to see if that fixes it.

**Comment by jzaefferer** [comment]
That doesn't quite explain why it fails for the `qunitjs` package, since that as a valid semver release (`1.20.0`). Thanks for looking into it.

**Comment by tolmasky** [comment]
quintjs also has an invalid semver version 1.20.0pre.

**Comment by tolmasky** [comment]
Was a 1.12.0pre pushed at some point (that we then picked up), but then replaced by 1.12.0-pre?

**Comment by tolmasky** [comment]
OK I think we fixed it. We're re-indexing now so it should be up in a little bit (I'll confirm here after its done). Separately we're looking into this strange -pre/pre issue. If the non-dashed versions never appeared then we have some strange issue on our end where we dropped it.

**Comment by KenanY** [comment]
Hmm, maybe relevant on the subject of that hyphen being added?:

> at some point in the past the primary registry (`registry.npmjs.org`) was cleaned up so that all of the semver returned by it is valid

https://github.com/npm/npm/issues/9657#issuecomment-141499065

**Comment by boucher** [comment]
Just a quick heads up that this has been fixed on our end.

**Comment by tolmasky** [comment]
Alright, it should now be working. Sorry about that, we're going to look more at the base cause but it should now be functioning correctly. Let us know if there are any other issues and apologies for the initial problems!

**Comment by jzaefferer** [comment]
Looks good to me!
