### ISSUE TITLE
Improve phone number validation on enterprise signup page

### ISSUE THREAD

**Issue by seldo** [npm/newww#1447]
All we do right now is check that it's not empty:

https://github.com/npm/newww/blob/master/facets/enterprise/show-ula.js#L14

I'm sure a client-side regex can be found to validate something vaguely phone-numbery.

**Comment by iarna** [comment]
Validating international phone numbers is ... tricky? Due to the way telephone networks work, there's little in the way of standards. We can verify that it's a number with only `+` `(` `)` and `-` sprinkled in, but I would be cautious about requiring more than that and a (modest) minimum length.

**Comment by aredridel** [comment]
Indeed. I've seen phone numbers reach into the 30 digits before, if you count extensions and international stuff.

**Comment by seldo** [comment]
We can at least check that it is a) not blank and b) mostly alphanumeric?

**Comment by jonathanmarvens** [comment]
@aredridel I've always wondered how Google validates phone numbers, because their phone number validation in a lot of their products is __really__ good.

**Comment by aredridel** [comment]
They spider the whole web.

And usually they call the number to validate it.

**Comment by jonathanmarvens** [comment]
@aredridel They don't always call the number, and even when they do, I'm talking about the validation that takes place before even calling it. Usually, calling the number is done to make sure it's your number. (I'll find an example, cause I remember thinking about this just a couple months ago.)

**Comment by aredridel** [comment]
Interesting! Knowing them, they probably did it the hard way, and got validation rules in place for every country. And then keep that list up to date.

**Comment by jonathanmarvens** [comment]
It turns out Google open-sourced their phone number validation library (it's a native C++ library): https://github.com/googlei18n/libphonenumber … someone probably already made a Node.js module for this.

**Comment by jonathanmarvens** [comment]
Oh wait, there's a pure JavaScript version in the same repo: https://github.com/googlei18n/libphonenumber/tree/master/javascript … nice!

**Comment by aredridel** [comment]
Oh neat!


... dat build process tho.

**Comment by jonathanmarvens** [comment]
Yup. Haha. Ain't nobody got time for Ant!

**Comment by jonathanmarvens** [comment]
I hate that it's so Closure-specific 😕.

**Comment by aredridel** [comment]
For sure. You can usually use those projects outside of a Closure environment, but it takes some coddling. Anything on the registry that's a port or wrapping of this?

**Comment by jonathanmarvens** [comment]
Also, woah: https://github.com/googlei18n/libphonenumber/blob/7a7e07708b0ec6b90ccb45b701d2799228ccc8c1/javascript/i18n/phonenumbers/metadatalite.js#L250-L5175 …

**Comment by jonathanmarvens** [comment]
Google always takes the hard route. Haha. (Which is good for everyone else when they decide to open-source it!)

**Comment by jonathanmarvens** [comment]
@aredridel: https://www.npmjs.com/package/google-libphonenumber …

**Comment by aredridel** [comment]
That seems reasonable.
