### ISSUE TITLE
fire AdWords 1x1 on npm On-Site signed-ULA confirmation

### ISSUE THREAD

**Issue by cowperthwait** [npm/newww#1453]
during On-Site signup, after a trialler agrees to the ULA by clicking _Agree to license_ at https://www.npmjs.com/enterprise-start-signup#free-trial fire the following event:

```
<!-- Google Code for On-Site Free Trial Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 965451981;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "z8e7CMaL92AQzcGuzAM";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/965451981/?label=z8e7CMaL92AQzcGuzAM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
```

**Comment by cowperthwait** [comment]
adding @kaseybyrne as a follower

**Comment by aredridel** [comment]
Is this the only way to send this event? It might be much smoother if the server can post the conversion, rather than the client. (Can I sign in and see how this is configured?)

**Comment by cowperthwait** [comment]
@aredridel 
Docs on other ways to post conversions — e.g., a GET request to a conversion URL — are here:
https://developers.google.com/app-conversion-tracking/android/conversion-tracking-server

Speaking generally, however: We will need a means to fire 1x1s on arbitrary pages; this is pretty much table stakes for any ad network, as well as other tools with which we intend to integrate, e.g., Optimizely. Can we lay the groundwork to support this by installing a tag manager, e.g., GTA or Segment?

**Comment by aredridel** [comment]
If this were a simple 1x1 it'd be easy, but this isn't a 1x1. It's a script.

**Comment by cowperthwait** [comment]
@aredridel 
Docs on other ways to post conversions — e.g., a call to the AdWords API — are here:
https://developers.google.com/app-conversion-tracking/android/conversion-tracking-server

Speaking generally, however: We will need a means to fire script calls / 1x1s on arbitrary pages; this is pretty much table stakes for any ad network, as well as other tools with which we intend to integrate, e.g., Optimizely. Can we lay the groundwork to support this by installing a tag manager, e.g., GTA or Segment?

**Comment by cowperthwait** [comment]
> (Can I sign in and see how this is configured?)

Invite to join adwords with administrative access sent, 2015-11-16, 14:54; snag me on Slack if you have trouble.

**Comment by aredridel** [comment]
accepting!

**Comment by aredridel** [comment]
Need confirmation of acceptance?

**Comment by cowperthwait** [comment]
They sure are thorough! Accepting now.

```
On Mon, Nov 16, 2015 at 3:01 PM, Google AdWords <adwords-noreply@google.com> wrote:
Hello,

Aria Stewart has accepted your invitation to share the same AdWords account. This individual has created his/her own email address and password to sign in.

To protect yourself and your AdWords account, we recommend that you contact this person on the phone or face-to-face, and confirm that he or she accepted your invitation. Then, grant this person access to your AdWords account at https://adwords.google.com/um/AccountAccess

Once access is granted, this user will be able to sign in to and manage the AdWords account using a Google Account distinct from yours. If you have any questions, please visit https://adwords.google.com/support/aw/?hl=en_US

Sincerely,

The Google AdWords Team
```

**Comment by aredridel** [comment]
I think I figured this out. Just use the 1x1 that's buried in the middle of that. OMG. SO MUCH PAIN for such a simple action

**Comment by aredridel** [comment]
implemented in https://github.com/npm/newww/pull/1506
