### ISSUE TITLE
change main nav / footer from 'private modules' to 'private packages'

### ISSUE THREAD

**Issue by ncawthon** [npm/newww#1476]
when we go GA (that's General Access) for TnO, please change the taxonomy of our main nav and footer elements from 'private modules' to 'private packages'.

**Comment by ncawthon** [comment]
the display text would be "npm Private Packages" and utilize the URL structure /private-packages/
our On-Site product would have the display "npm On-Site" and utilize the URL structure /on-site/

**Comment by ncawthon** [comment]
...and _another_ thing... add "npm Open Source" as a nav item, with the URL structure /open-source/

**Comment by ncawthon** [comment]
resulting in the nav structure: 

npm On-Site   |    npm Private Packages    |   npm Open Source   |   documentation   |   blog   |    support

/on-site/               /private-packages/               /open-source/

(this will remove jobs and npm-weekly)

**Comment by aredridel** [comment]
Any reason to gate this on timing with GA, or can it go live immediately?

**Comment by ncawthon** [comment]
content would not be ready before GA

**Comment by ncawthon** [comment]
@jonathanmarvens URLs updated in the above comment, made them absolute, but we should first try relative paths instead...

**Comment by ncawthon** [comment]
Yaaaaas!
