### ISSUE TITLE
Last row in team page is misaligned

### ISSUE THREAD

**Issue by seldo** [npm/newww#1518]
The last row in the table is messed up:
![screenshot 2015-11-17 17 36 14](https://cloud.githubusercontent.com/assets/185893/11230212/c1db821a-8d51-11e5-83a9-9d8df426c8d4.png)

There is a last-child rule in the CSS responsible:
```
.org-table tbody tr:last-child td:last-child {
    text-align: left;
    width: auto;
}
```

**Comment by ncawthon** [comment]
https://github.com/npm/newww/pull/1533
