### ISSUE TITLE
Team description field enter is unstyled and not populated with existing text

### ISSUE THREAD

**Issue by seldo** [npm/newww#1521]
![screenshot 2015-11-17 17 42 28](https://cloud.githubusercontent.com/assets/185893/11230308/9e22d14c-8d52-11e5-9161-78792038b87c.png)

This should be bigger and there should be some text explaining what this is for.

**Comment by jonathanmarvens** [comment]
Hey, @ncawthon. Just fixed this in #1542.

**Comment by ncawthon** [comment]
@jonathanmarvens - too quick
