### ISSUE TITLE
readmes don't auto-link URLs in markdown

### ISSUE THREAD

**Issue by jiyinyiyong** [npm/newww#1560]
For example the same README.md is highlighted on GitHub, but turns you to be text on http://npm.org:
https://github.com/teambition/volubile-ui
https://www.npmjs.org/package/volubile-ui

**Comment by aredridel** [comment]
Indeed. We don't auto-link URLs (yet?)

Worth discussing, though probably needs to be an issue with marky-markdown.

**Comment by zeke** [comment]
A shelved implementation from a while back: https://github.com/npm/marky-markdown/pull/19

**Comment by pavelloz** [comment]
I think it has been fixed because i cant see any link in mentioned github readme that isnt a link on its npmjs equivalent.

I used the repo from the first post to test it.

**Comment by jiyinyiyong** [comment]
Confirmed.
https://raw.githubusercontent.com/teambition/volubile-ui/master/README.md
