### ISSUE TITLE
restrict deletion of Super Admin from org

### ISSUE THREAD

**Issue by snopeks** [npm/newww#1564]
At this time, if the super admin deletes themselves from their org, they end up in a limbo state where they can't view the expected org tabs, and cannot be added back as super admin. 

I tried it myself, and here's how it plays out: I removed myself as super admin.  The org is still listed in my subscriptions, and payment is still happening (confirmed by the "manage billing" page) and this seems to be allowing the other members to use the org. It seems technically I still own the org, but can’t view any of the org tabs + can't add new members. When I go to my profile page, ```0 organizations``` is what shows up. 

Since there can only be 1 super admin, and we can't change it currently, it makes sense to disallow the deletion of this role. cc @chrisdickinson @rockbot

**Comment by seldo** [comment]
High priority on this, please.

**Comment by seldo** [comment]
This looks like this:

![pasted image at 2015_11_24 03_29 pm](https://cloud.githubusercontent.com/assets/185893/11385399/539af048-92cd-11e5-83ff-230198957515.png)
