### ISSUE TITLE
Quality-of-life feature request: access underlying repo via URL

### ISSUE THREAD

**Issue by sidd** [npm/newww#1567]
Often I find myself wanting to access the underlying Github repository for an npm package, so I'll use `npm repo <pkg>` on the command line to do this.

It would be great if there was some shortcut to do this in the browser, i.e. visiting https://npmjs.com/package/co/repo (or https://npmjs.com/co/repo) would redirect to https://github.com/tj/co. 

I only glanced through the routes files and didn't see anything like this, so please excuse me if this feature already exists.

**Comment by zeke** [comment]
http://ghub.io

**Comment by sidd** [comment]
:thumbsup:
