### ISSUE TITLE
Changing my profile picture on npmjs.com

### ISSUE THREAD

**Issue by httpNick** [npm/newww#1568]
Hello,

My profile: https://www.npmjs.com/profile/httpnick

I created a wordpress account which the link took me to from the npm update profile page. I added my email address (the same as my npmjs.com email address). uploaded and linked an image to my email address and I do not see changes on npm. Please let me know if I missed some steps or anything I can check to figure this out.

Thanks!

**Comment by aredridel** [comment]
Is your picture G rated?

**Comment by httpNick** [comment]
It looks like it is PG @aredridel

**Comment by aredridel** [comment]
That'd do it.
