### ISSUE TITLE
Large READMEs still get truncated

### ISSUE THREAD

**Issue by lroal** [npm/newww#1581]
This is still a problem. My README still gets truncated. Is this a problem with npm package or the npm website ? I am using npm 1.4.28
Referencing #397

**Comment by aredridel** [comment]
Not sure, I can take a look later after the holiday here, but do consider upgrading `npm`. The `1.x` series is end of life and contains known bugs that will not be fixed.

**Comment by aredridel** [comment]
Which package is yours? I'd love to investigate.

**Comment by lroal** [comment]
Hi, I just tried to publish a package to npm with npm@3.5.0 and node@0.12.7 and it still truncates. I unpublished the package since it was a dummy package, but I sure can publish it again.

**Comment by aredridel** [comment]
Does it truncate in the registry (`npm show yourpackage readme`) or just on the website?

**Comment by lroal** [comment]
the registry is truncated

**Comment by lroal** [comment]
the truncated package: https://www.npmjs.com/package/rdbreadmetest

**Comment by aredridel** [comment]
Alright. Then that is an issue for either the registry or cli teams. I'm chasing that down.

**Comment by lroal** [comment]
Thanks in advance.

**Comment by aredridel** [comment]
Sure thing! So. It's a registry limit, probably no longer needed in our current architecture, but we have not raised it yet.

The limit is 64kb.

**Comment by lroal** [comment]
Are you going to raise it ?

**Comment by aredridel** [comment]
Not immediately, but we're building a tracking issue internally for it. It will not be immediate, possibly not even soon. Need to figure out how that goes in with our user priorities.

**Comment by aredridel** [comment]
I'm going to close this issue since it is not actually a bug in `newww`, even if we do display the truncated data, but we _are_ tracking it internally.
