### ISSUE TITLE
Unable to remove organization member

### ISSUE THREAD

**Issue by atombender** [npm/newww#1584]
Clicking on the remove icon, on the members page, gives me a page containing this JSON result:

```
{"statusCode":403,"error":"Forbidden"}
```

**Comment by aredridel** [comment]
What organization and member? (if you don't want it to be public, feel free to report via support@npmjs.com)

**Comment by atombender** [comment]
Emailed. Thanks.

**Comment by aredridel** [comment]
Sure thing. Closing to resolve via support.
