### ISSUE TITLE
After organization conversion, approx. 40 spurious un-deletable teams in UI

### ISSUE THREAD

**Issue by dpratt** [npm/newww#1589]
We converted our account to an organization today, and now the Teams tab lists 40+ 'teams', all with auto-generated names. Attempting to delete or view them results in a 404 error in the browser.

**Comment by jonathanmarvens** [comment]
@dpratt A fix will be in production soon! Thank you.

**Comment by jonathanmarvens** [comment]
Hi, @dpratt, this issue is now fixed! Closing this issue. (Please feel free to reopen if you still have issues!)

Thank you!

**Comment by billinghamj** [comment]
We have this issue as well...

**Comment by jonathanmarvens** [comment]
@billinghamj: How so?

**Comment by billinghamj** [comment]
see: http://imgur.com/w4wFHLO

**Comment by jonathanmarvens** [comment]
@billinghamj: Oh, I see. This is not the same issue. Please create a new issue describing what's going on and we'll address it there. Thank you!

**Comment by billinghamj** [comment]
Oh okay, thanks.

**Comment by jonathanmarvens** [comment]
@billinghamj: CC me on the new issue, so that I see it!

**Comment by billinghamj** [comment]
For future ref of anyone who comes across this - you can delete these teams via the CLI, as follows:

0. make sure you have other teams with access to the packages
0. run `npm team ls [org]` (e.g. `npm team ls foo`)
0. run `npm team destroy [org]:@[org]/[team]` for each team (e.g. `npm team destroy foo:@foo/blah_88f8a12c-0ed8-4b1c-8fcf-bfe12846ee96`)
