### ISSUE TITLE
License Link for package goes to someone else's GitHub license

### ISSUE THREAD

**Issue by tlhunter** [npm/newww#1621]
Check out this package:
https://www.npmjs.com/package/grille

In the right column, the license link (BSD-2-Clause license) goes to someone else's repository:
https://raw.github.com/justjohn/transit-api/master/LICENSE

The relevant line in the packages package.json:
```
  "license": "BSD-2-Clause",
```

The package itself has a LICENSE.md file in the root. The expected behavior would be a link to the exact LICENSE.md file used for the project, or to go to opensource.org page.

**Comment by jonathanmarvens** [comment]
@soldair: I'm assigning this issue to you, because it's more closely related to your work than mine. (I'll ping you with more info!)

**Comment by bengourley** [comment]
Hi, is there an update on this? Lots of my modules are BSD-CLAUSE-2 and the npm website links it off to someone else's GitHub… e.g.

https://www.npmjs.com/package/currency-symbol-map
https://www.npmjs.com/package/crud-subservice
https://raw.githubusercontent.com/justjohn/transit-api/master/LICENSE

Thanks!

**Comment by jonathanmarvens** [comment]
@bengourley: We did find out what the problem was, but I don't think a fix was pushed yet. I'll check and update this issue as necessary. Thank you!

**Comment by soldair** [comment]
The bug is that the first person to publish a module with that license string has their license url associated with it. This is not useful data for the website.

i propose that
1) we stop linking to licenses 

or 

2) if the license is a valid spdx license we should use the offical url for it
otherwise we should not link it. Users can find it in the repo

**Comment by ChALkeR** [comment]
Related: https://www.npmjs.com/package/mqlight — «proprietary license», with a link to http://opensource.org/licenses/proprietary.

Should be fixed by the solutions @soldair proposed.

**Comment by aredridel** [comment]
This is fixed by #996, thank you @kemitchell!
