### ISSUE TITLE
How about GitHub autorisation and integration?

### ISSUE THREAD

**Issue by 3y3** [npm/newww#166]
GitHub is a main source where users stored their npm projects.
So, it will be interesting to allow users to log in with github account (and link it to already existed npm account)

The second interesting point is the service for github (like Travis CI service), which, for example can listen to a new tag event and automatically publish new version.

Do you have something like that in the plans?

**Comment by zeke** [comment]
We think it will be very useful to support github-based logins and oauthy stuff in the future, but it's not on our roadmap right now. Will revisit at a later date. Thanks!
