### ISSUE TITLE
magic number in nav CSS

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/newww#1681]
looks like the first anchor element is left aligned, while all others are right aligned
this supports the idea that the first anchor will be the npm-expansions anchor, but this is not always true

e.g.

```
nav
  div.container
    a(href="http://www.npmjs.com/on-site") npm On-Site
    a(href="https://www.npmjs.com/private-packages") npm Private Packages
    a(href="https://www.npmjs.com/open-source") npm Open Source
    a(href="https://www.npmjs.com/support") support
```

produces 
![screenshot 2015-12-18 at 4 54 04 pm](https://cloud.githubusercontent.com/assets/1163554/11910267/2ce31c76-a5a8-11e5-905e-3e19df3d6fcb.png)

**Comment by aredridel** [comment]
Time to flexbox :allthethings:

**Comment by ncawthon** [comment]
https://github.com/npm/newww/pull/1684
