### ISSUE TITLE
How to hide a prerelease version?

### ISSUE THREAD

**Issue by moroshko** [npm/newww#1682]
At the moment, npmjs.com shows version 1.10.3 of `eslint`:

[![enter image description here][1]][1]

However, running `npm show eslint versions` reveals an alpha version:

    [ '0.0.4',
      '0.0.5',
      ...
      '1.10.2',
      '1.10.3',
      '2.0.0-alpha-1' ]

What causes npm to hide the alpha version?

---

I published an alpha version of `react-autosuggest`, and was hoping that npm will hide it as well, but npm shows it:

[![enter image description here][2]][2]

Any ideas how could I hide an alpha version from npm?

  [1]: http://i.stack.imgur.com/w64Rl.png
  [2]: http://i.stack.imgur.com/W0fMr.png

http://stackoverflow.com/q/34394017/247243

**Comment by aredridel** [comment]
Tag the version you want installed by default with 'latest', and publish prereleases under a different tag.

**Comment by aredridel** [comment]
https://docs.npmjs.com/cli/dist-tag
