### ISSUE TITLE
border on paid/unpaid toggle too thin to see

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/newww#1688]
browser: chrome on chromebook pixel

looks like this: 
![screenshot 2015-12-22 at 12 55 48 pm](https://cloud.githubusercontent.com/assets/1163554/11962129/70398342-a8ab-11e5-922d-01beb24f67be.png)

**Comment by aredridel** [comment]
@ncawthon this is definitely a thing for me too on a retina macbook. Thoughts? Just thicken border? Other treatment?
