### ISSUE TITLE
Converted organization has many arbitrary undeletable teams

### ISSUE THREAD

**Issue by billinghamj** [npm/newww#1705]
See:

- http://imgur.com/w4wFHLO
- http://imgur.com/0Ch6d69

cc: @jonathanmarvens

**Comment by aredridel** [comment]
You'll want to contact support@npmjs.com for how teams and orgs work to improve this -- this is not a website issue, those teams are in fact present in your registry data.

**Comment by billinghamj** [comment]
@aredridel: Indeed but I am unable to control them. They cannot be edited, deleted, etc.

If the data is incidental and should be ignored, perhaps the website should not show them.

This is clearly a bug (with UX if not technical), though unclear where the problem lies.

**Comment by aredridel** [comment]
Yes, I'm just saying it's not something the website can fix -- if you cannot edit them, that may be a bug, and contacting support is the fastest way to get that resolved.

**Comment by billinghamj** [comment]
Thanks

**Comment by billinghamj** [comment]
For future ref of anyone who comes across this - you can delete these teams via the CLI, as follows:

0. make sure you have other teams with access to the packages
0. run `npm team ls [org]` (e.g. `npm team ls foo`)
0. run `npm team destroy [org]:@[org]/[team]` for each team (e.g. `npm team destroy foo:@foo/blah_88f8a12c-0ed8-4b1c-8fcf-bfe12846ee96`)

**Comment by aredridel** [comment]
:+1:
