### ISSUE TITLE
Markdown sometimes not rendered properly

### ISSUE THREAD

**Issue by chojrak11** [npm/newww#1706]
https://www.npmjs.com/package/express-session#compatible-session-stores
It must have worked previously. Related: https://github.com/expressjs/session/issues/248

**Comment by stubbornella** [comment]
@https://app.asana.com/0/76448700613771: This is indeed strange, but I highly doubt this is an issue on our end. It has to be something with marky-markdown, no?

**Comment by aredridel** [comment]
Oops. We're ending up with asana URLs leaking out into communication.

**Comment by aredridel** [comment]
(marky-markdown is also 'our end')

**Comment by cianclarke** [comment]
I've done some digging on this issue in https://github.com/expressjs/session/issues/248 - looks like this is a better fit for either npm/marky-markdown, or markdown-it/markdown-it.

- npm/marky-markdown attempts to render github `README.md` files in the manner in which they are displayed in GitHub repos. 
- markdown-it/markdown-it attempts to render markdown to spec. 

I've tried to determine in https://github.com/expressjs/session/issues/248 if the markdown in question is to-spec or not, but I guess here it's more a question of should npm/marky-markdown attempt to closely implement GitHub's more forgiving spec?

**Comment by ashleygwilliams** [comment]
hey! i maintain marky-markdown and am going to move this to the marky repo! thanks for filing. i'll be sure to CC you.
