### ISSUE TITLE
Restart paying for an org when you are a current customer who did not cancel after org was created the first time

### ISSUE THREAD

**Issue by jefflembeck** [npm/newww#1708]
The backbone for this is already in place.

User who cancelled their org, realizes they made a mistake:

1. Go to the *payment info page* for the org
1. Click restart button
1. Success banner is shown saying "Congrats, you've reinstated your org"

or 

1. Go to the the *billing page* for the user
1. Click restart button
1. Success banner is shown saying "Congrats, you've reinstated your org"

NB: there are two pages they can reinstate the org from

Implementation details:
All we should need is a button on the org payment info page that switches when the org is canceled, which is already on the object we're sending the the template - https://github.com/npm/newww/blob/master/handlers/org.js#L159

Restarting the org is a matter of posting to `/org/{org}` with an `updateType` in the payload of `restartOrg`.

**Comment by stubbornella** [comment]
@ncawthon - please change the wording and add design comps

**Comment by jefflembeck** [comment]
Issue resolved and in production
