### ISSUE TITLE
Restart paying with a non-customer

### ISSUE THREAD

**Issue by jefflembeck** [npm/newww#1709]
If somebody stops paying us, but then wants to start paying us again by restarting an org. That should definitely be an option!

1. Paid user clicks "cancel" 
1. Realizes next month they made a mistake, and wants to restart
1. User visits settings/billing (linked from profile)
1. Sees a list of cancelled orgs with a button beside them saying "restart"
1. Click restart
1. Enter credit card info
1. Redirected to subscriptions tag (settings/billing) now with the org moved into the active section
1. Show success banner "you successfully reinstated @orgname."

Here's how this needs to work:

Go to restart org
-> Customer is not found
-> Get Billing Details
-> Create new customer
-> Create new org license for said customer
-> Attempt to sponsor each user.

This issue does not include the following work: 

* Visits cancelled org page - sees call to reinstate it 
* We ultimately need to stop really deleting users, but @chrisdickinson is too busy for now (EDIT: stripe makes this impossible - if we get rid of billing info, we get rid of the licensed user)

**Comment by jefflembeck** [comment]
Issues that are related: https://github.com/npm/license-api/issues/101
https://github.com/npm/newww/issues/1587#issuecomment-162998485

**Comment by stubbornella** [comment]
@chrisdickinson - does this issue description match your expectations?

**Comment by stubbornella** [comment]
@ncawthon - can you please insert designs that match from the billing information tab?

**Comment by stubbornella** [comment]
@ncawthon - what wording would you use to link the person to billing information?

**Comment by chrisdickinson** [comment]
> We ultimately need to stop really deleting users, but @chrisdickinson is too busy for now

Responded here: https://github.com/npm/license-api/issues/100#issuecomment-168856163 — We should not plan to have license-api not really delete customers on delete requests.

> Attempt to sponsor each user.

This could be drawn from the sponsorship list for the old license, or alternatively from the list of members of the org. Do we have a preference on which it's drawn from?

**Comment by jefflembeck** [comment]
@chrisdickinson for the first one, yeah, totally impossible, we can work around that
for the second one, I think the latter will do just fine

**Comment by jefflembeck** [comment]
Issue resolved and in production
