### ISSUE TITLE
Under some circumstances the version on the website fails to update

### ISSUE THREAD

**Issue by iarna** [npm/newww#1729]
As described in https://github.com/npm/npm/issues/11073

This is happening via travis, so it seems likely that multiple publishes are happening at the same time.

On the first attempt, the user got a 401– they corrected their auth and ran it again and reported getting a 403 (can't publish over an existing package).

1.10.0 exists in the registry, is the most recent release and it is also set as latest.

**Comment by stubbornella** [comment]
Closing to track internally.

**Comment by aredridel** [comment]
This likely got fixed with the `tar-follower` changes @soldair shipped
