### ISSUE TITLE
A `<div>` in the description of the package breaks the appearance of the project page

### ISSUE THREAD

**Issue by lovasoa** [npm/newww#1730]
I have the string `<div>` in the description of one of my packages ([react-contenteditable](https://www.npmjs.com/package/react-contenteditable)), and it breaks the appearance of the project page.

See the [`package.json`](https://github.com/lovasoa/react-contenteditable/blob/master/package.json) of the project.

**Comment by aredridel** [comment]
I'm not seeing the break -- what part is broken for you?

**Comment by lovasoa** [comment]
![This is how it is rendered](https://cloud.githubusercontent.com/assets/552629/12207963/d2bad464-b65a-11e5-9142-07d417de0bf6.png)

**Comment by aredridel** [comment]
Oh, I see! Makes sense. Alright! We've had a few README issues, I'm going to file it to solve with those.

**Comment by lovasoa** [comment]
If you look at the html, you will see `<p class="package-description">React component representing a </p>` whereas you should see `<p class="package-description">React component representing a &lt;div&gt; with editable contents</p>`

**Comment by lovasoa** [comment]
And it should look like that
![capture du 2016-01-08 22-58-59](https://cloud.githubusercontent.com/assets/552629/12208059/72d754cc-b65b-11e5-8160-91536817761a.png)

**Comment by lovasoa** [comment]
The problem is that the html is not escaped correctly.

**Comment by aredridel** [comment]
Yup!

**Comment by aredridel** [comment]
This is fixed in production now!
