### ISSUE TITLE
update CONTRIBUTING to include instructions for security issues

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/newww#1733]
security vulnerabilities should not be reported on public issues.
instead, they should be privately emailed to a mailing list.

the rust language has a great example of a security policy here: https://www.rust-lang.org/security.html

related: #1732 

thoughts? also cc/ @ceejbot

**Comment by stubbornella** [comment]
Looks like a good thing to me. @ceejbot @aredridel @isaacs, can you weigh in?

**Comment by isaacs** [comment]
This is a good idea, and an easy doc fix.

Our head of security is @seldo, but if @ashleygwilliams or anyone else wants to take a crack at writing a policy, that seems fine.  Our long detailed (and probably eventually public) security policy is at https://github.com/npm/internal-docs/blob/master/security/security-policy.md

**Comment by seldo** [comment]
The instructions do not need to say much more than "email security@npmjs.com and wait at least 1 working day for a reply" and I agree, this is a good idea.

**Comment by stubbornella** [comment]
Ok, great, @ashleygwilliams do you want to submit a PR?

**Comment by ashleygwilliams** [comment]
sure thing @stubbornella. incoming.

**Comment by ashleygwilliams** [comment]
PR here: https://github.com/npm/newww/pull/1770

**Comment by stubbornella** [comment]
Fantastic!
