### ISSUE TITLE
Dev/test/staging should not submit real data to Stripe

### ISSUE THREAD

**Issue by stubbornella** [npm/newww#1737]
We might be sending data to the real stripe account rather than to test. Please verify that all dev, test, staging data is using the right api key/endpoint. The stripe docs can be found here:

https://stripe.com/docs/testing

It looks like we are doing this correctly, this ticket is just to confirm.

/cc @aredridel

**Comment by aredridel** [comment]
It's definitely sending test mode for all those because otherwise the test card number `4242424242424242` would fail. The integration tests do this, so we're sure it's test mode for the test environments.

**Comment by aredridel** [comment]
What was the impetus for this?

**Comment by stubbornella** [comment]
A question from @jefflembeck, but I misunderstood. Closing now.
