### ISSUE TITLE
unable to subscribe to individual private modules

### ISSUE THREAD

**Issue by snopeks** [npm/newww#1743]
In an attempt to test something about private modules, I discovered that the flow for signing up for private modules is not working. 

Here's what happened:
profile page --> "sign up for PM" --> fill out CC form --> get kicked to subscription page where I get the message "you do not have any subscriptions". I tried again from the subscription page --> "sign up for PM", same issue. 

Just in case of gremlins, I logged out/logged back in, tried again, but still encountered the same issue.

**Comment by snopeks** [comment]
Turned out to be an email issue: I had already purchased private modules on another account using that same email. Changing the email enabled me to purchase private modules & the purchase flow worked perfectly. There could be a more useful error for this situation :+1:

**Comment by aredridel** [comment]
Reopening so we can fix this with at least an error message!

**Comment by stubbornella** [comment]
Close in favor of #1744
