### ISSUE TITLE
Mustache-style tags within README code blocks get stripped out

### ISSUE THREAD

**Issue by passcod** [npm/newww#1750]
It appears that the Markdown renderer incorrectly strips out Mustache-style double-curlies in code blocks. Compare:

### Markdown source
https://raw.githubusercontent.com/Marak/faker.js/master/Readme.md

```
``` js
console.log(faker.fake('{{name.lastName}}, {{name.firstName}} {{name.suffix}}'));
// outputs: "Marks, Dean Sr."
```
```

(Using [Greek varias](https://en.wikipedia.org/wiki/Ancient_Greek_accent) to replace backticks there.)

### GIthub readme
https://github.com/Marak/Faker.js

![screenshot from 2016-01-15 10-38-53](https://cloud.githubusercontent.com/assets/155787/12338553/0a1dc046-bb75-11e5-8f54-2fe4428f7857.png)

### NPM readme
https://www.npmjs.com/package/faker

![screenshot from 2016-01-15 10-39-23](https://cloud.githubusercontent.com/assets/155787/12338571/17405324-bb75-11e5-8d17-87db4ccf7b4c.png)

**Comment by aredridel** [comment]
Well shucks!

**Comment by ashleygwilliams** [comment]
closing in favor of https://github.com/npm/marky-markdown/issues/160

@passcod i've mentioned you on the issue so you get updated :) (p.s. PRs welcome!)
