### ISSUE TITLE
Does a temporary 404 on Github affect NPM?

### ISSUE THREAD

**Issue by franciscop** [npm/newww#1757]
I have recently been flagged temporarily (although I don't know how long) in github as a bot. This had the effect that **all of my repositories returned a 404**. Does it affect in any way to NPM projects?

Things that could happen:

- NPM thinks the repository is deleted and thus delets/marks as 404 the package (extreme)
- NPM unlinks the package from the repository since it's a 404 now. New versions are not updated.

Now it's solved, but only because I happened to be on github now. Had I been offline for few days it might have been worse. This is something to consider (if it hasn't been considered already) since other modules might be required by others, and thus making it a bigger problem.

So, how does NPM treat a temporary 404 on Github's repository that is linked on a module?

**Comment by KenanY** [comment]
Nothing happens.

**Comment by franciscop** [comment]
Awesome, thanks!
