### ISSUE TITLE
Contact Us form errors on submit

### ISSUE THREAD

**Issue by ehsalazar** [npm/newww#1760]
We received reports from users identifying an issue on the [Contact Us](https://www.npmjs.com/support) page when attempting to submit support requests. 

Reproduced flow:
- enter information in form fields
- select `I need help with something`
- submit

Upon submit, the following error was given:
```
1453139817524:www-11-west.internal.npmjs.com:5177:ijgcgdtb:48273
```

I did not test the `This is a general inquiry` or `I'm reporting a security issue` options.

![contactus](https://cloud.githubusercontent.com/assets/7298179/12398841/fd758f60-bdca-11e5-9b8f-41a1f19f83ee.png)

**Comment by aredridel** [comment]
Looks like the zendesk token is wrong after Friday. I'll update that.

**Comment by aredridel** [comment]
THis should be fixed now.
