### ISSUE TITLE
CMS page /npm/private-packages/learn-more is 500 ing

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/newww#1764]
https://www.npmjs.com/npm/private-packages/learn-more/

linked to from https://www.npmjs.com/npm/private-packages

reported by https://twitter.com/jolyon_russ/status/689473207859036160 @jolyonruss

**Comment by aredridel** [comment]
Adding logging in #1766

**Comment by ashleygwilliams** [comment]
appears to still be 500 on staging after @aredridel's patch merged+pushed.

**Comment by aredridel** [comment]
`Error: Invalid page returned`

`{"id":318,"html":"","title":"learn-more","slug":"learn-more","stylesheets":["https://assets.npmjs.com/uploads/assets/npm-theme.css?v=2016-1-12-19-39-37"],"scripts":["https://assets.npmjs.com/uploads/assets/theme.js?v=2016-1-12-19-39-37"]}` is the data

**Comment by aredridel** [comment]
The CMS has no HTML for this page, so it's being rejected.

**Comment by ashleygwilliams** [comment]
ping @seldo @cowperthwait

**Comment by ashleygwilliams** [comment]
not sure if this is on the HumanMade side or due to changes that happened on that page last week.

**Comment by aredridel** [comment]
Yeah. Notably, this has a nested URL slug, which I'm not sure work right.

**Comment by seldo** [comment]
This specific page is now restored and we are tracking the larger "why does the CMS lose pages?" issue over at https://github.com/npm/marketing-integration/issues/106 so recommend closing this.

**Comment by aredridel** [comment]
Thank you!

**Comment by ashleygwilliams** [comment]
thanks ya'll :)
