### ISSUE TITLE
Remove tag feature

### ISSUE THREAD

**Issue by MrMormon** [npm/newww#1777]
As there is no apparent way to search/group by tag, and good, terse descriptions provide any information a tag list could, I propose we get rid of this little 'feature.'

**Comment by KenanY** [comment]
What are tags? Or do you mean keywords?

**Comment by MrMormon** [comment]
Keywords, yes. They show up under the version numbers of search results with tag icons.

**Comment by KenanY** [comment]
@MrMormon Ohhh I see now. You can search by keyword (like this: https://www.npmjs.com/browse/keyword/framework) so I think those should ideally be links.

**Comment by MrMormon** [comment]
Where the heck was that documented?! Thanks.

**Comment by KenanY** [comment]
@MrMormon They are linked at the package page: https://www.npmjs.com/package/express
