### ISSUE TITLE
How to install a package a long with its devDependencies & Revert back to version 0.1.4

### ISSUE THREAD

**Issue by Dindaleon** [npm/newww#1787]
I am working on this project https://github.com/Dindaleon/hapi-react-starter-kit

I published it to npmjs but I am unable to install it on my pc because it complains that some dev dependencies that are required to build the project are missing.

So, I want to know how I can tell npmjs to install the devDependencies after installing the package and before running the build script.

Also, I bumped my project's versions trying to figure this out without any luck. Thus, I would like to know if there is an admin who could please revert my project from version 0.1.6 back to 0.1.4 on npmjs.

It can be found at: https://www.npmjs.com/package/hapi-react-starter-kit

Thanks.

**Comment by aredridel** [comment]
You can unpublish versions if you like, with `npm unpublish yourmodule@0.1.6`, or you can change the `latest` tag with `npm dist-tag add latest yourmodule@0.1.4`.

**Comment by aredridel** [comment]
If you need further support with the registry, contact support with support@npmjs.com
