### ISSUE TITLE
Markdown Rendering Issues

### ISSUE THREAD

**Issue by jhuckaby** [npm/newww#1788]
I have discovered a number of Markdown rendering bugs on npmjs.com, which I have compiled into a package with examples:

https://www.npmjs.com/package/npm-markdown-bugs

Compare this to the same exact Markdown syntax on GitHub, and you can see the issues:

https://github.com/jhuckaby/npm-markdown-bugs

I figured this would be better than entering 5 separate issues.  But if you would prefer that, please let me know.

Thanks!

**Comment by ashleygwilliams** [comment]
hi! could you refile this on our markdown parser repo: https://github.com/npm/marky-markdown ?

very happy to work on this! thanks for such a comprehensive issue

**Comment by revin** [comment]
Oh wow, fantastic test case, @jhuckaby; thanks!

**Comment by jhuckaby** [comment]
Ah, will do @ashleygwilliams, thanks!  I had no idea you had a separate repo for markdown stuff.  Submitting issue there now.

You're welcome @revin!  Glad to help!
