### ISSUE TITLE
Org payment info tab is missing payment info

### ISSUE THREAD

**Issue by seldo** [npm/newww#1807]
My account has a valid CC associated with it; this screen says no payment info on file.

![screenshot 2016-01-27 11 26 13](https://cloud.githubusercontent.com/assets/185893/12625487/f08e190a-c4e8-11e5-9b31-8dcee9d49afc.png)

**Comment by seldo** [comment]
NB: this only happens if I cancelled payment for the org. I can see how it happens (no subscription, therefore no accompanying payment info) but there are other ways to get payment info.

**Comment by stubbornella** [comment]
Just to clarify, this happens when you cancel payment for the org and then restart payment for that same org?

**Comment by seldo** [comment]
This happens if I cancel payment for the org and then look at that org's payment info tab. "N/A" is correct because I'm not being billed. "No payment on file" is incorrect, because the system has my payment info on file for my other orgs.
