### ISSUE TITLE
on-site flow: shorten the trial form

### ISSUE THREAD

**Issue by isaacs** [npm/newww#1811]
https://www.npmjs.com/onsite#free-trial

Delete company, number of employees, and interests fields so that the button is above the fold when they click the link to the form.

(Maybe also put "first name" and "last-name" as half-width next to one another?  Less important.)

**Comment by stubbornella** [comment]
So, if I'm understanding the ask vs the proposed solution, you'd like the button to start the trial above the fold? And you are suggesting removing fields and/or using more horizontal space?

**Comment by isaacs** [comment]
Sorry, I wasn't clear!

Yes, we want the button above the fold.

Also, we want to exclude some fields that are rarely filled out anyway, and create unnecessary friction.

The bit about putting the first and last name inline is 100% overstepping and suggesting a design implementation.  Feel free to reject that bit outright :)

**Comment by stubbornella** [comment]
This has been prioritized in the teams backlog.
