### ISSUE TITLE
Analytics concerns for relating the last visible ad to commerce events

### ISSUE THREAD

**Issue by aredridel** [npm/newww#1816]
From discussion on unrelated tickets:

@stubbornella:
> I don't know that we can use the analytics events to store "last visible ad" when the commerce event happens on a totally different page.

@cowperthwait:

> If Marketing were left to our own devices, I would MacGuyver a way to store both last-viewed-ad and close-box state in GA custom environment variables — ~~but these only persist for the session~~ which we could scope to persist for lifetime of a GA cookie (default: 730 days). This approach would satisfy my requirement to remember this for purposes of conversion tracking, but would not satisfy some other requirements, such as persistence across machines ~~/ login states / sessions.~~

**Comment by stubbornella** [comment]
In discussions with @cowperthwait, marketing is fine with punting on persistence across machines at least for now. I told them that was much more expensive than the other asks.

**Comment by cowperthwait** [comment]
In an ITA with @seldo, we’ve agreed on pushing an npm GUID into GA at a future date; when we do this, we can revisit using this for cross-device persistence.

**Comment by aredridel** [comment]
Closing since this is captured in pivotal and taken into account
