### ISSUE TITLE
Double quote " in package description appears as &quot; on npmjs.com

### ISSUE THREAD

**Issue by jesseschalken** [npm/newww#1818]
If you put a double quote `"` in your package description, eg `"description": "foo\"bar"`, the double quote will appear as `&quot;` on the package page. This suggests something is escaping HTML special characters twice.

Example:
- NPM page: https://www.npmjs.com/package/bugsnag-agent
- `package.json`: https://github.com/jesseschalken/bugsnag-agent/blob/master/package.json

![image](https://cloud.githubusercontent.com/assets/1559204/12670086/bdd8e1ac-c6b9-11e5-9485-e02f886e8bc6.png)

**Comment by aredridel** [comment]
this is a duplicate of #1789. Follow along there!

**Comment by jesseschalken** [comment]
Ah, I couldn't find the existing issue. Thanks.
