### ISSUE TITLE
*README.md* renders to http://readme.md which resolves to some GitHub repo's README.md

### ISSUE THREAD

**Issue by fibo** [npm/newww#1842]
Today I've just released [this package on npm](https://www.npmjs.com/package/not-defined).

Something really strange happened: in the [Annotated source section](https://www.npmjs.com/package/not-defined#annotated-source) I wrote `*README.md*` in the documentation, and it is rendered to a link to `http://README.md` which lands on [README.md of GitHub repo echonest/pyechonest](https://github.com/echonest/pyechonest/blob/master/README.md).

If you fix it, please I would like to understand how it happens this.

**Comment by aredridel** [comment]
Closing in favor of npm/marky-markdown#146, which is where the details lie.
