### ISSUE TITLE
Markdown: non link rendered as link

### ISSUE THREAD

**Issue by natewallace** [npm/newww#1860]
The plain text `options.name` is being rendered as a link with the url being `options.name`.  You can see an example of this here:

https://www.npmjs.com/package/build-bundle

**Comment by jefflembeck** [comment]
This is related to https://github.com/npm/newww/issues/1842, which unfortunately is because our markdown parser automatically generates links of valid domain names.

This is being addressed here: https://github.com/npm/marky-markdown/issues/146

Closing as a duplicate. Thank you for filing!
