### ISSUE TITLE
package description is showing HTML strings

### ISSUE THREAD

**Issue by UnsungHero97** [npm/newww#1864]
I've just published a new package to npm, [kryptnostic-js](https://www.npmjs.com/package/kryptnostic-js), and the page for my package is rendering an HTML string in the `package-description` element:

![screen shot 2016-02-09 at 2 37 45 pm](https://cloud.githubusercontent.com/assets/440299/12933017/b662da70-cf3a-11e5-8888-862269875245.png)

![screen shot 2016-02-09 at 2 34 12 pm](https://cloud.githubusercontent.com/assets/440299/12933016/b65f5774-cf3a-11e5-92e9-888922e60f90.png)

It looks like what's being added is related to the badges, but the badges themselves are rendering correctly. Why is this happening? Could it be because I've omitted the `description` field in `package.json`?

**Comment by aredridel** [comment]
Yes, the description being left out will do that, so we use a line from your readme; there's a bug there #1722 and #1731 are related and we're working on that. the short fix is to include a description in your package.json.

**Comment by UnsungHero97** [comment]
thank you!
