### ISSUE TITLE
`__proto__` in package.json description interpreted as `<strong>` on web

### ISSUE THREAD

**Issue by ljharb** [npm/newww#1886]
1) https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-proto-to-assign/package.json#L4
2) https://www.npmjs.com/package/babel-plugin-transform-proto-to-assign

Looks like the `__`-wrapped `proto` is being converted into being `<strong>`-wrapped, and then not even rendered as HTML.

**Comment by aredridel** [comment]
Yeah, this is actually related to #1864 and #1722, so I'm going to close in favor of those. We actually need to render markdown when the source for the line is the readme, but as text when it's from package.json, and that's gonna take some rejuggling of the internal code that does this, both in marky-markdown probably, and this repo.

**Comment by ljharb** [comment]
Thanks, makes sense
