### ISSUE TITLE
Unpublish glitch

### ISSUE THREAD

**Issue by roman-io** [npm/newww#1898]
I have 2 issues with unpublish:
1. a public package that still appears on the site after it was unpublished using npm cli.
2. I had a subscription on npm site and few private test packages, now when my subscription is no longer valid - I can't unpublish my private test packages(clean my page on npm), even that no-one has access to them.

**Comment by aredridel** [comment]
This is not a website issue -- you'll want to email support at support@npmjs.com and they can look into the registry issues.
