### ISSUE TITLE
Make github less special

### ISSUE THREAD

**Issue by iarna** [npm/newww#190]
So, currently github repositories are given special treatment, with short-names for repositories allowed and other information inferred from it (eg, issue's, etc). I have changes in the pipeline for the CLI (as a part of multi-stage install) to broaden this to include other hosted services (currently bitbucket and gitlab).   Before that goes live and people publish with it, I'd like to see the website updated to support it too.

I'll be happy to put together a pull request when the time comes, I just wanted to give you all a heads up in advance.

**Comment by zeke** [comment]
@iarna we will happily support other source code thingies, when the time comes!
