### ISSUE TITLE
Markdown Table Styling

### ISSUE THREAD

**Issue by clintonhalpin** [npm/newww#1900]
Hi!

I'm curious is there a way to make the table styling in readme's appear like an actual table ( and closer to github )? Mainly I'd expect the text in cells to be left aligned ( for legibility ) and possibly you'd add borders around the rows. 

Just something that sort of bugged me, feel free to close if this is dumb. Thanks!

![screen shot 2016-03-05 at 12 33 39 pm](https://cloud.githubusercontent.com/assets/523933/13549224/30f7cf00-e2cf-11e5-81ae-e5e2bb69755b.png)

**Comment by aredridel** [comment]
Duplicate of #1819

**Comment by clintonhalpin** [comment]
@aredridel My bad sorry about that!
