### ISSUE TITLE
a11y: Use speaking values for alt-attribute of img

### ISSUE THREAD

**Issue by Ryuno-Ki** [npm/newww#1901]
Subscribing to your rss feed I noticed some non-speaking alt-attributes for `<img>`s

For example, in [How to Build A Slackbot + Deploy an App to Heroku for Absolute Beginners](http://blog.npmjs.org/post/128237577345) the images have only "image" as alt-attribute - which would be shown, if the reader has connectivity issues or reads it offline (as in my case).

I'd like to encourage your writers to spend some time thinking about it. You can do better :-)

Especially the screen shot showing a single line of code is unaccessible to blind readers (it would only read "image" …).

**Comment by aredridel** [comment]
Which RSS feed?

**Comment by Ryuno-Ki** [comment]
http://blog.npmjs.org/rss

**Comment by aredridel** [comment]
Aha! I'll ping the @npm/marketing team as a heads up, but this is not the right repo -- this is the codebase for the website.

**Comment by aredridel** [comment]
Thanks for the report!

**Comment by cowperthwait** [comment]
Hi @Ryuno-Ki: Thanks for the headsup on this. I’m not 100% sure how the Markdown => HTML parsing works on Tumblr (who host our blog), but it _should_ be the case that image tags make it over intact. I’ll take a look and make a point to remind our team to always label their images.

**Comment by cowperthwait** [comment]
@nexdrew: see above in re the images accompanying your post. cc/ @ashleygwilliams

**Comment by Ryuno-Ki** [comment]
@aredridel Then add the correct repo to [Where to get help from npm](http://blog.npmjs.org/post/129318099330) :-)

To me, the blog is part of the website.
