### ISSUE TITLE
Using & in the package discription results in it getting displayed incorrectly

### ISSUE THREAD

**Issue by rnjailamba** [npm/newww#1911]
<p class="package-description">Simple url generation for Node JS , Express JS that works! [[www.abc.xyz?def=ghi&amp;amp;jkl=mno]</p>

Photo of issue - 
http://imgur.com/xLfY5nc

Link -
https://www.npmjs.com/package/urlgenerator

**Comment by aredridel** [comment]
Duplicate of #1864

**Comment by rnjailamba** [comment]
@aredridel 
My package.json has the following description - 
  "description": "Simple url generation for Node JS , Express JS that works! [www.abc.xyz?def=ghi&jkl=mno]",

**Comment by aredridel** [comment]
Yep. Things from the `description` field should be interpreted as text; they are not; things from the README should be limited markdown. They are HTML escaped. We've got some un-tangling to do there but it's weirdly layered to fix.

**Comment by rnjailamba** [comment]
Ok
but alls good on my profile page if you check.
https://www.npmjs.com/~rnjailamba12

**Comment by aredridel** [comment]
Oh nice catch. That makes me wonder if the other thing that is wrong with that field happens there.

**Comment by rnjailamba** [comment]
:)
and its fine on the listing page as well - 
http://imgur.com/9a16Rh0
