### ISSUE TITLE
Broken link to license

### ISSUE THREAD

**Issue by mervick** [npm/newww#1922]
For example [angular](https://www.npmjs.com/package/angular) license is linked to [http://spdx.org/licenses/MIT](http://spdx.org/licenses/MIT), but should be [http://spdx.org/licenses/MIT.html](http://spdx.org/licenses/MIT.html)

**Comment by aredridel** [comment]
Ooh, thank you!

I'm investigating with spdx.org to see if this is an oversight on their part.

**Comment by aredridel** [comment]
Looks like spdx.org is making some changes and it should work soon

**Comment by mervick** [comment]
Now, it's works.
