### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by arb** [npm/newww#1926]
I published an RC version (7.0.0-rc1) of the "good" package https://www.npmjs.com/package/good. Immediately after publishing, I used `npm dist-tag` to tag the previous major version (6.6.0) as "latest". However, when I go to the npm package listing page, it is showing the 7.0.0-rc1 README file and is extremely confusing to the users. Is there something I need to do to tell npm to reaload or rebuild that packages README file?

**Comment by aredridel** [comment]
That's on the long to-fix list ... for now, a new patch or prerelease of 6.6.x would bump it. Sorry for the dust!
