### ISSUE TITLE
Table not respecting markdown cell alignment.

### ISSUE THREAD

**Issue by jdalton** [npm/newww#1933]
Tables are not respecting markdown cell alignment.
See [package/lodash-webpack-plugin](https://www.npmjs.com/package/lodash-webpack-plugin#feature-sets) for an example of the issue.

The cells are aligned with `:---` which signals left alignment.

```md
| Feature | Description  |
|:---|:---|
| `shorthands`   | Iteratee shorthands for `_.property`, `_.matches`, & `_.matchesProperty`. |
| `collections`  | Support for objects in “Collection” methods like `_.each`, `_.filter`, & `_.map`. |
| `currying`     | Support for `_.curry` & `_.curryRight`. |
```
which should render as

| Feature | Description  |
|:---|:---|
| `shorthands`   | Iteratee shorthands for `_.property`, `_.matches`, & `_.matchesProperty`. |
| `collections`  | Support for objects in “Collection” methods like `_.each`, `_.filter`, & `_.map`. |
| `currying`     | Support for `_.curry` & `_.curryRight`. |

**Comment by vitali-ausianik** [comment]
Did someone have a chance to take a look on this issue?

**Comment by revin** [comment]
The sanitizer used in [npm/marky-markdown](https://github.com/npm/marky-markdown) is stripping the `style` attributes from the rendered `<th>` and `<td>` elements. @jdalton would you terribly mind moving this over there for us to talk about?

**Comment by revin** [comment]
actually @jdalton never mind I got it covered; opened [npm/marky-markdown#212](https://github.com/npm/marky-markdown/issues/212) for this.

**Comment by jdalton** [comment]
Moved to https://github.com/npm/marky-markdown/issues/212.
