### ISSUE TITLE
dates and versions of "packages people 'npm install' a lot" are stale 

### ISSUE THREAD

**Issue by jdalton** [npm/newww#1946]
The displayed dates and versions of "[packages people 'npm install' a lot](https://www.npmjs.com/#explicit)" look super stale:

<img width="100%" src="https://cloud.githubusercontent.com/assets/4303/15717457/fb5e3378-27db-11e6-8c68-a28e7fe153dc.png">

**Comment by jdalton** [comment]
Anything I can do to help?

**Comment by jdalton** [comment]
It looks like it could be related to [npm-explicit-installs](https://github.com/npm/npm-explicit-installs).

**Comment by jdalton** [comment]
\cc @bcoe

**Comment by bcoe** [comment]
@jdalton last I checked redis' expiry is seconds not mili-seconds:

https://github.com/npm/npm-explicit-installs/blob/master/index.js#L91

^ so I think that might be caching for 150,000 days.

sure enough:

```sh
ttl __npm_explicit_installs
(integer) 3966843
```

Mind opening an issue on `npm-explicit-installs` and closing this?

As for https://github.com/npm/newww/issues/1948, this is an issue with a recent database replacement. We're missing the cron job that generates these listings, expect a fix soon.

**Comment by jdalton** [comment]
Just a heads up the site is still showing old info.
