### ISSUE TITLE
/electron produces a strange 404

### ISSUE THREAD

**Issue by zeke** [npm/newww#1954]
Typically, a shorthand URL like https://www.npmjs.com/express will redirect to https://www.npmjs.com/package/express

But https://www.npmjs.com/express leads to an unusual 404 page (without the wombat).

Why is that?

**Comment by zeke** [comment]
![screen shot 2016-06-13 at 1 51 15 pm](https://cloud.githubusercontent.com/assets/2289/16022686/f4aa6394-316d-11e6-920f-3f9204bbb612.png)

**Comment by fabiosantoscode** [comment]
Can reproduce!

I use this all the time as it's really easy to use Firefox's address bar completion to find npm and just type in a package name.

**Comment by joaojeronimo** [comment]
can reproduce

**Comment by sholladay** [comment]
This seems to be fixed. :D

**Comment by aredridel** [comment]
This is indeed fixed!
