### ISSUE TITLE
Stale package page showing

### ISSUE THREAD

**Issue by erikrose** [npm/newww#1960]
4 days ago, I published v1.1 of fathom-web, but [the page](https://www.npmjs.com/package/fathom-web) still shows v1.0 as the latest, complete with the old readme. 1.1 downloads just fine via `npm install`.

**Comment by peterjcaulfield** [comment]
@erikrose you can update the latest tag with `npm tag fathom-web@v1.1 latest`. This **should** fix the latest tag and README but I'm having stale README issues on NPM even with new version/dist tag.

**Comment by erikrose** [comment]
It turns out there was already a "latest" tag:
```
[11:31:45 ~/Code/fathom]% npm dist-tag ls
latest: 1.1.0
```
So I deleted it and tried making it over again. However, I ran into errors:
```
[14:58:24 ~/Code/fathom]% npm dist-tag rm fathom-web latest
npm -latest: fathom-web@1.1.0
[14:58:33 ~/Code/fathom]% npm dist-tag ls
npm ERR! dist-tag ls Couldn't get dist-tag data for fathom-web
[14:58:37 ~/Code/fathom]% npm dist-tag add fathom-web@1.1.0 latest
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "dist-tag" "add" "fathom-web@1.1.0" "latest"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! No dist-tags found for fathom-web
```
The deprecated `tag` command hung:
```
[14:58:52 ~/Code/fathom]% npm tag fathom-web@1.1 latest
npm WARN tag This command is deprecated. Use `npm dist-tag` instead.
npm ERR! registry error parsing json
npm ERR! registry error parsing json
▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
^C
```
Finally, I just did a meaningless version bump and republished, and that fixed the page:
```
[15:01:31 ~/Code/fathom]% npm publish
+ fathom-web@1.1.1
```
