### ISSUE TITLE
how to use ng2-range sider ?

### ISSUE THREAD

**Issue by ankitpachori** [npm/newww#1966]
Hi, 
i want to use ng2-range slider in my project.For this i am using this command npm install --save ng2-slider-component but i am getting error like this--
![ng2](https://cloud.githubusercontent.com/assets/19892558/16917633/0b260d12-4d20-11e6-9889-3d4e8c0f1380.jpg)
  How can i fix this?

**Comment by aredridel** [comment]
This isn't an issue with the npm website, so I'm closing your issue. 

Feel free to contact support@npmjs.com with support questions.

However, this is a failure compiling the `zopfli` module -- which actually looks to be non-fatal, instead it is a warning that an optional module failed to install. Complete output would be much more useful in diagnosing this issue and whether there is in fact one. 

You can confirm what modules are installed in your project with `npm ls`, and this may be useful for figuring out what state you're in.
