### ISSUE TITLE
Having problem with up and running vagrant.

### ISSUE THREAD

**Issue by mehrdadrafiee** [npm/newww#265]
I have installed VirtualBox and Vagrant. But when I try `vagrant up` in the root repo, the following error message pops up:

**The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.**

**If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.**

I looked it up but found nothing. Any help would be greatly appreciated.

Thanks.

**Comment by zeke** [comment]
We are in the process of phasing out the development VM, in favor of a staging environment with a fully replicated registry, a redis, etc that will be accessible to the public. We're also refactoring the test suite to not rely on locally-running services like elasticsearch, redis, couch, etc. This will allow public users to get up and running with the newww codebase more easily.

All of this work is happening in the r2 branch. Follow along at https://github.com/npm/newww/pull/325
