### ISSUE TITLE
People as a first order organizing concept of the npm site

### ISSUE THREAD

**Issue by rod11** [npm/newww#278]
GitHub won over BitBucket because it was people focused.

npm should aim to be the same.   Nice People Matter

- "People" as a top level nav - they are authors, curators and users
- The people directory should have a useful top level nav highlighting most direct downloads, most installed, most starred, most robust comment sections, etc

**Comment by rod11** [comment]
Hi Zeke,

Part of the request was a directory of people.   It's an important social component to be able to search for companies or individuals and for us to take steps to highlight those people.

Perhaps we should chat in person and discuss the idea in more detail.

Many thanks,

- Rod

**Comment by zeke** [comment]
Closing this. As time permits, we can populate the issues queue with more granular tasks.
