### ISSUE TITLE
display badges on package page

### ISSUE THREAD

**Issue by zeke** [npm/newww#287]
To keep READMEs looking sharp and readable, the package presenter currently applies a CSS class of `superfluous` to all badge image `p` tags, and then the stylesheet hides them:

- https://github.com/npm/newww/blob/3bddc4e8b1c2edfa4fbd75a75d8a17a433d9c3c4/facets/registry/presenters/package.js#L334-L345
- https://github.com/npm/newww/blob/3bddc4e8b1c2edfa4fbd75a75d8a17a433d9c3c4/assets/styles/readme.styl#L40-L41

Users are likely to ask where there README badges have gone. They answer is, CSS heaven. No, the answer is (or will one day be).. the sidebar. Let's make a thing that collects all the badges and displays them alongside other stats, like download/issue/PR counts.

We could also start supporting a `badges` (or similar) property in package.json.

**Comment by dougwilson** [comment]
This is such a pain to alter my registry entry after every time I publish to get my badges to show up. Any idea about this change?

**Comment by zeke** [comment]
Yeah gonna ship it as soon as I can.

**Comment by dougwilson** [comment]
Cool. Sorry, I hate to pester :) I just wanted to make sure it wasn't forgotten, rather than try to rush it :)

**Comment by zeke** [comment]
No worries. I want to ship it as much as you do. It will not be forgotten. :)

**Comment by knownasilya** [comment]
fist bump :fist:

**Comment by zeke** [comment]
It's old news by a few days now, but badges are back!

Also, the `superfluous` class name has been eradicated entirely, in favor of more meaningful appellations like `badge`, `package-name-redundant`, and `package-description-redundant`. Save yourself the `git blame`: I take full responsibility for this poor choice of words.

Also, the [express logo](https://www.npmjs.com/package/express) is no longer being singled out and removed, though I still think it looks better without. Maybe npm's [eventual support of package icons](https://github.com/npm/newww/issues/291#issuecomment-65514297) will help settle this score... :)

**Comment by Fishrock123** [comment]
\o/

**Comment by ljharb** [comment]
Thanks!!

**Comment by bcomnes** [comment]
:dancers:
