### ISSUE TITLE
show a better error than [object Object] when login values are missing

### ISSUE THREAD

**Issue by zeke** [npm/newww#362]
![screen shot 2014-12-09 at 4 26 46 pm](https://cloud.githubusercontent.com/assets/2289/5369095/b8f0a834-7fc3-11e4-9d3a-943e64eefc00.png)

**Comment by RichardLitt** [comment]
Huh. Got this when using 1Password without using the username, just the password. Same problem, but now it is 'Invalid username or password' if the name is included and the pass is wrong. I suspect this [line](https://github.com/npm/newww/blob/master/services/user/methods/user.js#L18) throws an error. Would fix by download vagrant in a cafe !== fun.

**Comment by zeke** [comment]
Fixed

**Comment by RichardLitt** [comment]
:+1:
