### ISSUE TITLE
Package markdown readme is not formatted

### ISSUE THREAD

**Issue by parshap** [npm/newww#369]
The readme for the *[fleet][]* package is currently rendering as plain text for me. I expected the markdown rendered to html like other packages. [See screenshot][screenshot].

I thought it may be that the file extension is `.markdown`, but it looks like that case is [very liberally handled][handled].

[fleet]: https://www.npmjs.com/package/fleet
[screenshot]: https://cloud.githubusercontent.com/assets/332258/5369526/0268736a-7fca-11e4-82cd-4a6d41cd66a8.png
[handled]: https://github.com/npm/newww/blob/2695942392b54b4cfc5fd93288f8f59a07da59a0/facets/registry/presenters/package.js#L156

**Comment by parshap** [comment]
Looks like this is fixed because the fleet page is now rendering correctly and I haven't seen this issue anywhere else recently.

**Comment by zeke** [comment]
thanks for following up!
