### ISSUE TITLE
Logged in image doesn't exist

### ISSUE THREAD

**Issue by twolfson** [npm/newww#376]
Expected behavior: After logging in, I should see my profile image in the upper right

Actual behavior: After logging in, a broken image is displayed next to my name. However, my profile page properly displays my image

Screenshot:

![Screenshot](https://cloud.githubusercontent.com/assets/902488/5372332/9bcf1422-800c-11e4-97e4-16cfbd817f3d.png)

To prevent regressions like this in the future, it might be worthwhile to add visual regression tests to your test suite. I wrote an article on them a while ago so more frameworks have popped up since:

http://twolfson.com/2014-02-25-visual-regression-testing-in-travis-ci

**Comment by zeke** [comment]
Note to selves: Ensure that the `user-info` gravatar is being generated by `./lib/avatar.js` (in the r2 branch)

**Comment by twolfson** [comment]
Upon logging in, I am still seeing the issue. When is the next deployment scheduled so I can verify it is patched?
