### ISSUE TITLE
Profile image too big on half-width browser

### ISSUE THREAD

**Issue by twolfson** [npm/newww#377]
When I have 1 screen on my laptop, I sometimes use half-width for browsers (540px). I noticed that at this width, my profile image becomes very very large. I believe this is not intentional behavior. Here are screenshots.

**540px width:**

![Half-width screenshot](https://cloud.githubusercontent.com/assets/902488/5372419/0d364b48-800e-11e4-8c85-27a73e6cd413.png)

**Larger width:**

![Larger width screenshot](https://cloud.githubusercontent.com/assets/902488/5372423/1c8a10fc-800e-11e4-9dd9-109349a506af.png)

**Comment by zeke** [comment]
The switch-to-mobile media query threshold for page width is lower now. It was 1100ish before and now it's something like 760, so unless your desktop browser window is very narrow, you'll still see the two column layout.

**Comment by twolfson** [comment]
Looks great, thanks!
