### ISSUE TITLE
Markdown lists with with newline renders with a code tag

### ISSUE THREAD

**Issue by MikkoH** [npm/newww#383]
I have lists with newlines in my markdown.

The second line of the list item is rendered in a `<code>` tag. Which produces really odd styling.

Compare:
https://github.com/jam3/clmdraw
and
https://www.npmjs.com/package/clmdraw

**Comment by zeke** [comment]
Hi @MikkoH. Take a look at https://www.npmjs.com/package/clmdraw and let us know if you're still seeing issues. Thanks!

**Comment by MikkoH** [comment]
I don't see any issues rendering anymore.

All good in the hood.
