### ISSUE TITLE
Add star counts and dependent counts to package pages stats section.

### ISSUE THREAD

**Issue by jdalton** [npm/newww#401]
With the npm site redesign, which looks great, the [top 10 list](https://www.npmjs.com/browse/star) for starred packages was lost. The shift to bury stats is OK but at the moment the stars/dependents stats don't appear to be available anywhere on the site (uncool). I know I can use [other](http://npm-stat.com/charts.html?package=lodash)-[tools](https://www.npmjs.com/package/npm-stats) but having the info available at a glance on npm's site was really handy. It would rock if the stats for number of  dependents and stars where included on the existing stats section of package pages.

The stats section:
<img src=https://cloud.githubusercontent.com/assets/4303/5385412/137b82fc-8077-11e4-9adb-0f80ed2c1377.png height=40% width=40%>

Also it would be nice if the lists had clear/consistent rank indications.
It's not super clear at the moment when its ranking by columns-top-down or by rows-left-right.

The dependents list on [the homepage](https://www.npmjs.com/#depended) (top-down):
<img src=https://cloud.githubusercontent.com/assets/4303/5385350/a2ab839c-8076-11e4-8168-5d20e1e6b0b8.png height=75% width=75%>

The dependents list on [browse/depended](https://www.npmjs.com/browse/depended) (left-right):
<img src=https://cloud.githubusercontent.com/assets/4303/5387202/2918b8f0-808b-11e4-9d9b-8e3ce042fe22.png height=90% width=90%>

**Comment by zeke** [comment]
Closing because this is a pretty amorphous issue. Please open smaller, more specific issues if necessary.
