### ISSUE TITLE
Protocol relative urls are prefixed with "null:" using github flavored markdown

### ISSUE THREAD

**Issue by ugate** [npm/newww#403]
Using `[protocol relative url](//example.com)` will result in `<a href="null:example.com">protocol relative url</a>` in `README.md`

Carried over from: npm/npm-www#894

**Comment by zeke** [comment]
@ugate can you provide an example of this?

**Comment by ugate** [comment]
[releasebot](https://www.npmjs.com/package/releasebot) used to one of them, but it looks like it's been fixed since I opened the issue. Thanks for the follow-up!
