### ISSUE TITLE
Section missing in Express README

### ISSUE THREAD

**Issue by dougwilson** [npm/newww#409]
There is a "People" section in the Express README that is missing content on the www.npmjs.org website.

GitHub: https://github.com/strongloop/express#people
npmjs.org: https://www.npmjs.com/package/express#people

The cause is because https://github.com/npm/newww/issues/287 is too aggressive and assumes the only thing in the paragraph with the badge is the badge/other badges. In this case, the badge was inline with text. Seems likely this is hiding text for other packages.

**Comment by zeke** [comment]
People are back :)

https://www.npmjs.com/package/express#people

**Comment by dougwilson** [comment]
Yay! :)
