### ISSUE TITLE
Links not rendered in "camp" README

### ISSUE THREAD

**Issue by dougwilson** [npm/newww#410]
The README at https://www.npmjs.com/package/camp seems to not be rendering the links. I assume the old npm site did.

/cc @espadrine

**Comment by zeke** [comment]
We are now using [markdown-it](http://registry.npmjs.org/mq) which adheres to ComonMark. Perhaps a PR to https://github.com/espadrine/sc/edit/master/README.md is in order.

![screen shot 2015-01-28 at 10 23 51 pm](https://cloud.githubusercontent.com/assets/2289/5953304/65a8272e-a73c-11e4-85e4-601d06d74ade.png)

via http://spec.commonmark.org/0.17/

**Comment by espadrine** [comment]
Done.
