### ISSUE TITLE
Broken link with 'CC0-1.0' license

### ISSUE THREAD

**Issue by nfriedly** [npm/newww#440]
When a package such as https://www.npmjs.com/package/express-secure-only sets it's license to `CC0-1.0`, the NPM page ends up with a broken link to http://opensource.org/licenses/CC0-1.0

I think the link *should* point to http://creativecommons.org/publicdomain/zero/1.0/ but no link at all might be good enough for things that aren't listed on opensource.org.

**Comment by linclark** [comment]
Looks like this was fixed in the linked issue, so I'm going to close it out.

**Comment by nfriedly** [comment]
This has actually not been fixed yet, or at least the fix hasn't been merged yet. The initial PR was closed in favor of two seperated ones: 

https://github.com/npm/newww/pull/665

And 

https://github.com/npm/oss-license-name-to-url/pull/1

**Comment by linclark** [comment]
Ah, thanks for the catch. Reopening.

**Comment by nfriedly** [comment]
No worries, I probably should have updated this one before.

**Comment by aredridel** [comment]
This is fixed by #996, thank you @kemitchell !
