### ISSUE TITLE
Fix invalid package name page layout

### ISSUE THREAD

**Issue by zeke** [npm/newww#446]
Following up on a comment here: https://github.com/npm/newww/issues/436#issuecomment-67279884

https://www.npmjs.com/package/%20abcdef doesn't look so hot:

![screen shot 2014-12-17 at 10 19 23 am](https://cloud.githubusercontent.com/assets/2289/5476366/30dcab96-85d6-11e4-98f3-3aef23fde5ed.png)

- Use centered layout
- Wrap package name of in quotes or code fencing or something.

**Comment by coleGillespie** [comment]
@zeke i think this can be closed
