### ISSUE TITLE
text-transform lowercase on all h1s intrudes on developer markdown files

### ISSUE THREAD

**Issue by focusaurus** [npm/newww#455]
This rule: https://github.com/npm/newww/blob/60eec2f5a984420779caf4a168fe0d43d122f11c/assets/styles/typography.styl#L45

IMHO intrudes too much on the README by npm package authors. Would you consider removing it and restore our uppercase letters to their full and rightful existence?

Also seems perhaps risky given javascript is case sensitive to broadly change case for the user-authored markdown files. Not that I think people are going to be putting code snippets in their `h1`s on a regular basis, just sayin'.

**Comment by zeke** [comment]
:+1:

**Comment by zeke** [comment]
Fixed: https://docs.npmjs.com/files/package.json#devdependencies

**Comment by focusaurus** [comment]
Thanks! :tada:
