### ISSUE TITLE
Please redirect old package.json doc URL

### ISSUE THREAD

**Issue by graue** [npm/newww#458]
Won't you please redirect

https://www.npmjs.org/doc/package.json.html

(which I'd bookmarked and referred to for ages as the reference on what goes in a package.json — and which now 404s) to the new URL, which appears to be

https://docs.npmjs.com/files/package.json

? Thanks in advance for keeping people's bookmarks working!

**Comment by zeke** [comment]
Hey @graue, you've probably updated your bookmark by now, but at long last this issue is fixed: https://github.com/npm/docs/pull/147

Give it a try! https://www.npmjs.org/doc/package.json.html
