### ISSUE TITLE
Autofocus on index

### ISSUE THREAD

**Issue by Antariano** [npm/newww#469]
I have seen issue #316 and understand it's argumentation. However, I think that on the index page, the 
autofocus should be applied. 
Personally, when I'm on the homepage, I want to start typing right away. 

This would work rather nicely:
```
<input name="q" 

{{#unless q}} autofocus="autofocus" {{/unless}} 

value="{{q}}" type="search" id="site-search" placeholder="find packages" tabindex="1" autocorrect="off" autocapitalize="off" />
```
I didn't create a PR right away because I understand we might want to discuss this.

**Comment by PixnBits** [comment]
related to #513

**Comment by PixnBits** [comment]
@Antariano In #513 the <kbd>/</kbd> key was suggested as a shortcut to search. Curious of your experience/feedback?

**Comment by zeke** [comment]
@Antariano we initially had autofocus enabled, but many users complained that it breaks keyboard page scrolling. You can now focus the search input on any page by pressing `TAB` or `/` or `-`.
