### ISSUE TITLE
Dockerize npm-www, running it using Docker / Fig

### ISSUE THREAD

**Issue by marcellodesales** [npm/newww#479]
Hi there,

I'm been evaluating the integration of npm-www with the Enterprise server as a hosted solution. As we are dockerizing our internal assets, I have been trying to dockerize the setup of the npm-www server using Docker and Fig using the "dev/go.js" method.

The current demo of the server running is at https://asciinema.org/a/15074. I'm planning to submit a pull request if there are interests on this... 

Questions
-----
* Is the "dev/go.js" the ultimate way of deploying the server? 
* Are all those steps required when running a production setup of the Enterprise NPM?
* Is the CouchDB server in "dev/go.js" setup the same as the one running on the Enterprise NPM?

I can certainly remove/adjust the steps so that running the npm-www could be easily integrated with a Dockerized version of the Enterprise NPM...

thanks!
Marcello

**Comment by marcellodesales** [comment]
Could someone explain the reason why replicate would fail?

```
npmRegistryRedisServer_1         | [1] 02 Jan 22:44:24.549 - 0 clients connected (0 slaves), 437000 bytes in use
npmregistryserver_1              | Running "/usr/local/bin/node" ["/usr/src/app/dev/replicate.js"]
npmRegistryRedisServer_1         | [1] 02 Jan 22:44:29.559 - 0 clients connected (0 slaves), 437000 bytes in use
npmregistryserver_1              | Running "/usr/local/bin/node" ["./node_modules/npm2es/bin/npm2es.js","--couch=http://192.168.4.201:15984/registry","--es=http://192.168.4.197:9200/npm"]
npmregistryserver_1              | did npm2es undefined
npmregistryserver_1              | 
npmregistryserver_1              | TypeError: Cannot read property '_rev' of undefined
npmregistryserver_1              |     at Request._callback (/usr/src/app/dev/replicate.js:81:21)
npmregistryserver_1              |     at self.callback (/usr/src/app/node_modules/request/request.js:373:22)
npmregistryserver_1              |     at Request.emit (events.js:95:17)
npmregistryserver_1              |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:971:8)
npmregistryserver_1              |     at ClientRequest.emit (events.js:95:17)
npmregistryserver_1              |     at Socket.socketErrorListener (http.js:1551:9)
npmregistryserver_1              |     at Socket.emit (events.js:95:17)
npmregistryserver_1              |     at net.js:833:16
npmregistryserver_1              |     at process._tickCallback (node.js:419:13)
npmregistryserver_1              | /usr/local/bin/node /usr/src/app/dev/replicate.js fell over: 8
npmregistryserver_1              | BEGIN FOLLOWING @ 0
```

I know that that line fails because of `dev/_auth.js`. What does exactly that script do?

**Comment by marcellodesales** [comment]
This is fixed by https://github.com/npm/newww/pull/485

**Comment by zeke** [comment]
Hi @marcellodesales. Thanks for this awesome contribution. However, I think it will not be necessary moving forward.

We are in the process of phasing out the development VM, in favor of a staging environment with a fully replicated registry, a redis, etc that will be accessible to the public. We're also refactoring the test suite to not rely on locally-running services like elasticsearch, redis, couch, etc. This will allow public users to get up and running with the newww codebase more easily.

All of this work is happening in the r2 branch. Follow along at https://github.com/npm/newww/pull/325
