### ISSUE TITLE
use another module instead of marked

### ISSUE THREAD

**Issue by fengmk2** [npm/newww#487]
marked has too many performance and security issues, like https://github.com/chjj/marked/issues/497.
And it also out of maintain for a long time.

These is a easy way to public a package with readme markdown to put npm website down. 

So please use use another module instead of marked, e.g. markdown-it.

**Comment by fengmk2** [comment]
cc @puzrin

**Comment by puzrin** [comment]
I'll be glad if it happens :) . If my help needed - let me know. [markdown-it](https://github.com/markdown-it/markdown-it) implements "honest" state machine, and is free of many problems of regexp-based parsers.

**Comment by dougwilson** [comment]
> is free of many problems of regexp-based parsers

like insane back tracking :)

**Comment by puzrin** [comment]
> like insane back tracking :)

There are ton's of problems in all markdown implementation (except markdown-it, lol). Even if parsers works without bugs, those are very difficult to extend with new syntax or modify existing one. That was the main reason why we did this project.

Second reason was having more pratice with effective use of v8 inline caches. As result - with not cheap plugin system markdown-it is still faster than marked and reference commonmark implementation.

**Comment by KenanY** [comment]
Hmm, it might be better to file this at [marky-markdown](https://github.com/zeke/marky-markdown)'s issue tracker? That's what newww is switching to (https://github.com/npm/newww/pull/480).

**Comment by fengmk2** [comment]
@KenanY the problem is marked, marky-markdown deps on marked, so marky-markdown still has this issue.

**Comment by KenanY** [comment]
@fengmk2 Exactly, so this is a marky-markdown issue?

**Comment by puzrin** [comment]
> so this is a marky-markdown issue?

@KenanY  I think, the fact that package with bad readme can fuckup newww is still newww issue, until fixed. And that's security issue.

I hope, you beleive and will not ask to demonstrate, LOL

**Comment by KenanY** [comment]
`¯\_(ツ)_/¯` just trying to point this in what I think is the correct direction. If there's a case of a bad README that marky-markdown does not handle properly at the moment, then it sounds to me like that case should be added to marky-markdown's tests.

**Comment by puzrin** [comment]
@KenanY no problem, duplicated report in that tracker. I just meaned, that it's better to keep this issue open too, because it's related to end users.

**Comment by zeke** [comment]
I was not aware of `marked`'s performance or security issues, so thanks for opening this ticket.

Like @KenanY mentioned, we'll soon be using `marky-markdown` for all markdown processing on www.npmjs.com and docs.npmjs.com, so let's continue the conversation at https://github.com/zeke/marky-markdown/issues/5
