### ISSUE TITLE
the npmjs.org doc index isn't hyper-linked

### ISSUE THREAD

**Issue by frankcash** [npm/newww#492]
https://docs.npmjs.com/misc/index

would be beneficial if this page was hyper-linked to corresponding documentation page

ref: https://github.com/npm/npm/issues/7065

**Comment by faiq** [comment]
this probably belongs on npm/docs.npmjs.com, considering thats the docs page

**Comment by frankcash** [comment]
okay

https://github.com/npm/docs.npmjs.com/issues/102
