### ISSUE TITLE
Escaped pipes in tables are ignored and considered as a new table column

### ISSUE THREAD

**Issue by iainvdw** [npm/newww#506]
See the documentation for https://www.npmjs.com/package/gulp-tasker#api. Github correctly shows the pipes in the table, whereas npmjs.org renders the escaping slash, plus the content after the pipes is rendered as a separate table column.

**Comment by TessMyers** [comment]
I'm also having this problem-  It looks like all the markdown tables are having the same issue with the new NPM layout. Here's an example of github display vs NPM table display: 
![screen shot 2015-01-11 at 12 07 56 pm](https://cloud.githubusercontent.com/assets/6635970/5696602/362358ac-998b-11e4-83b6-6d1fa5480787.png)
![screen shot 2015-01-11 at 10 09 43 am](https://cloud.githubusercontent.com/assets/6635970/5696604/3909ddc0-998b-11e4-8429-f02770859707.png)

**Comment by TessMyers** [comment]
No clue what changed in the last few days, but the tables look great now. Thanks!

**Comment by zeke** [comment]
See https://github.com/npm/newww/pull/382 and subscribe to https://github.com/npm/newww/issues/545 for updates.
