### ISSUE TITLE
Show GitHub contributor count on the package page

### ISSUE THREAD

**Issue by zeke** [npm/newww#508]
I find GitHub contributor counts to be insightful when assessing project "health". For packages with GitHub-based repositories, we could easily add a contributor count to the stats, just like we do with open issue and PR counts.

GitHub API doc: https://developer.github.com/v3/repos/#list-contributors

Where the code should go: https://github.com/npm/newww/blob/master/assets/scripts/github.js

This is a small, contained feature, and could be a good opportunity for someone in the community who wants to contribute.

**Comment by yashprit** [comment]
@zeke can I take this or is this something not planned yet

**Comment by zeke** [comment]
@yashprit I know @coleGillespie started on it a while back, but the effort kind of fizzled out, which is understandable. The Github API code we're running client-side is in definite need of a cleanup. It's kind of spaghetti-ish right now. It would be helpful to use promises or a lightweight async tool to handle all those ajax requests more cleanly.

@yashprit if you do submit a PR, start small and get the conversation going early. I wouldn't want you to put a bunch of work into something we can't ship.

**Comment by yashprit** [comment]
@zeke that make sense.

**Comment by zeke** [comment]
Work in progress: https://github.com/npm/newww/pull/824
