### ISSUE TITLE
Link to code of conduct 404 on policies/disputes

### ISSUE THREAD

**Issue by petecoop** [npm/newww#512]
https://www.npmjs.com/policies/disputes

Links to: https://www.npmjs.com/policies/conduct.md

Should be: https://www.npmjs.com/policies/conduct

**Comment by KenanY** [comment]
Hmm, might be an issue for the [npm/policies](https://github.com/npm/policies) repo?

**Comment by zeke** [comment]
newww currently fetches policies pages from github raw. This is not ideal. In the long-run we want newww to consume this content from docs.npmjs.com, either as a webservice (`https://docs.npmjs.com/content.json`) or an npm module (`npm install docs.npmjs.com --save`).

I created an issue on the docs site to track this: https://github.com/npm/docs.npmjs.com/issues/127
