### ISSUE TITLE
focus search input when / key is pressed

### ISSUE THREAD

**Issue by zeke** [npm/newww#513]
That's a convention, right?

We're already using mousetrap.js, so it should be trivial to add this feature.

**Comment by coleGillespie** [comment]
@zeke can you explain further how this should work?

**Comment by PixnBits** [comment]
I would suggest that on the index page the search box should be focused w/o needing a shortcut key pressed.
Other pages I like the shortcut.

@coleGillespie I'd guess something akin to
```javascript
Mousetrap.bind('/', function(e) {
    $('#site-search').focus();
});
```

**Comment by zeke** [comment]
@PixnBits is on the right track with that snippet, though I disagree about the autofocus-on-homepage suggestion. We had it that way originally and people freaked out. Apparently people use arrow keys to scroll..

**Comment by PixnBits** [comment]
Scroll? *Pfft* **Search** is where it's at :smile: 
Makes sense, though some indicator/reminder of the shortcut would be nice (at least for *my* use case :-S ).

I'm trying
```javascript
mousetrap.bind('/', function(e){
  $('#site-search').focus();
  // don't add '/' character to input element
  e.preventDefault();
});
```
and looks like its working. Not sure what the best file would be to add this...perhaps [index.js](https://github.com/npm/newww/blob/master/assets/scripts/index.js)?

Would we want to also place the cursor at the end of the existing text in the input (instead of the beginning)? Example, I already searched for 'oracle' and when I press <kbd>/</kbd> the cursor is put before the 'o'.

**Comment by PixnBits** [comment]
ah, I see what you're saying with #316

**Comment by silverwind** [comment]
I'd vote for just autofocus when navigating to the front page. Subsequent page loads should probably not focus. Maybe it's possible to let the arrow key events bubble up from the input to still retain scrolling?

**Comment by PixnBits** [comment]
Sweet, the <kbd>/</kbd> shortcut [is live](https://www.npmjs.com/)! Feedback on your usage?

**Comment by silverwind** [comment]
Works as expected, but as a user of a german keyboard, `/` is very hard to reach at`Shift` + `7` (Whoever designed that layout should burn in hell).

A convention I saw for this in other software is to also bind `-` which is at the same location the `/` is on an american keyboard. Would you consider taking a PR for this?

**Comment by zeke** [comment]
> Would you consider taking a PR for this?

Sure... let's try it and if it causes problems for people we can revisit.

**Comment by silverwind** [comment]
I'll research first if it's possible to rely on a key code or something for the key besides shift.

**Comment by PixnBits** [comment]
Sorry that PR took so long

**Comment by lordKnighton** [comment]
NIce, i was just about to open a `PR` asking why, now i know. At-least the shortcut **`/`** is awesome.
