### ISSUE TITLE
HTML comments in readme markdown not rendered correctly.

### ISSUE THREAD

**Issue by rwaldron** [npm/newww#514]
<img src="http://i.gyazo.com/baff1da6bad53c06f4c7a4f31621256b.png">

**Comment by zeke** [comment]
derp.

Let's sit on this for a day or two and see if the problem isn't solved by shipping https://github.com/npm/newww/pull/480

**Comment by dougwilson** [comment]
:ship: :ship: :ship:

**Comment by zeke** [comment]
A fix is up on staging now: https://staging.npmjs.com/package/johnny-five

Follow https://github.com/npm/newww/pull/480 for the nitty-gritty.

**Comment by rwaldron** [comment]
:heart: 

Thanks for the super fast turn around :)

**Comment by zeke** [comment]
At long last, this is fixed in production: https://www.npmjs.com/package/johnny-five
