### ISSUE TITLE
Too much margin on <hr /> makes my README.md look unpleasant.

### ISSUE THREAD

**Issue by jehoshua02** [npm/newww#520]
I just published a package and noticed the `<hr />` styles have `margin: 0 0 80px`. This messes up my `__NOTE__` blocks, which I've been doing lately as a good way to make them stand out.

```markup
---
__NOTE__: Blah blah.
___
```

---
__NOTE__: Blah blah.
___

https://www.npmjs.com/package/react-breakpoints-mixin

I would expect the styles to be similar to Github's rendered markdown.

**Comment by zeke** [comment]
Thanks for filing. A fix for this will go out with https://github.com/npm/newww/commit/2e1d80cdf3ec8d1268b15e288663e8c91a9fcaca via https://github.com/npm/newww/pull/480
