### ISSUE TITLE
JSX Syntax Highlighting on README.md

### ISSUE THREAD

**Issue by jehoshua02** [npm/newww#521]
I just published a package and noticed the jsx syntax highlighting is not exactly right.

https://www.npmjs.com/package/react-breakpoints-mixin

I would expect something closer to Github rendered markdown.

**Comment by zeke** [comment]
We've deployed some changes to readme parsing today, and have disabled syntax highlighting until we have time to get it right. The plan of record is to switch to pygments, which has support for jsx.

**Comment by jehoshua02** [comment]
Thanks @zeke.

**Comment by StJohn3D** [comment]
Should I use \`\`\`js or \`\`\`jsx in my npm README file to get proper syntax highlighting for jsx snippets?

**Comment by aredridel** [comment]
We use the `highlights` library to do the highlighting, so whatever it supports. We add `diff` and `nginx` languages in addition to the defaults, as in https://github.com/npm/marky-markdown/blob/master/package.json#L30-L31

If you want to file a feature request there if the defaults do not suffice, I think we could entertain that but would have to look at the specifics and fit it into project plans.
