### ISSUE TITLE
links in code styled markdown are not displayed properly

### ISSUE THREAD

**Issue by jdalton** [npm/newww#523]
See https://www.npmjs.com/package/lodash.noop.
The link to `lodash.noop` is not showing up despite being in the markdown as

```markdown
The [Lo-Dash](http://lodash.com/) function [`_.noop`](http://lodash.com/docs#noop) as a [Node.js](http://nodejs.org/) module generated by [lodash-cli](https://npmjs.org/package/lodash-cli).
```

**Comment by KenanY** [comment]
Looks like the code style is properly applied [on staging](https://staging.npmjs.com/package/lodash.noop) but yeah link still isn't there.

**Comment by jdalton** [comment]
I think this could be that they are reading the npm package description and removing the description that exists in the readme itself. This will cause problems for Lo-Dash in general as it restates the package.json description in the readme but provides links to relevant things as well.

**Comment by jdalton** [comment]
See https://github.com/lodash/lodash/tree/npm-packages/lodash.invoke#readme and https://github.com/lodash/lodash/tree/3.0.0-npm-packages/lodash._basefind#readme

**Comment by jdalton** [comment]
Is there a way to avoid this or known workaround?

**Comment by jdalton** [comment]
Currently the content is hidden in a `<p class="superfluous"> ... </p>` it uses a [`similarity` helper](https://github.com/npm/newww/blob/1b7cb0f2fcea250cfce99fe1d05f2bd772abe9cf/facets/registry/presenters/package.js#L353) to determine if it should be hidden or not. In this case it's not detecting that there are links in the description and that it should use the one in the readme over the json description field.

**Comment by zeke** [comment]
@jdalton is this still an issue?

**Comment by jdalton** [comment]
Nope ya'll rock.
