### ISSUE TITLE
Starring a package isn't working.

### ISSUE THREAD

**Issue by trusktr** [npm/newww#527]
I'm logged in, visiting https://www.npmjs.com/package/operative, then clicking the star. When I hit refresh, the start is gray, not red. WHen I visit my profile, I don't see operative in the list. I've tried this multiple times.

**Comment by trusktr** [comment]
It does work with `npm star operative` though.

**Comment by trusktr** [comment]
I'm able to replicate the issue by visiting a package I've starred, unstarring it from command line with `npm unstar package` then refreshing the package page. Breaks every time.

**Comment by zeke** [comment]
This is fixed now. Thanks for reporting.
