### ISSUE TITLE
README.md not being transformed into HTML.

### ISSUE THREAD

**Issue by trusktr** [npm/newww#528]
I'm visiting https://www.npmjs.com/package/thread.js, and this is what I see:

![screen shot 2015-01-10 at 2 59 03 pm](https://cloud.githubusercontent.com/assets/297678/5693623/438ffebc-98d9-11e4-97b3-82098f5ad674.png)

**Comment by trusktr** [comment]
No errors in the console.

**Comment by KenanY** [comment]
Fixed in staging: https://staging.npmjs.com/package/thread.js

**Comment by trusktr** [comment]
Interesting, it didn't happen when I unstarred https://www.npmjs.com/package/npool.

But cool glad to hear you found the bug?

**Comment by trusktr** [comment]
Wow, that's really cool staging has the `#` linked headings for the READMEs. I like that.

**Comment by zeke** [comment]
Fixed: https://www.npmjs.com/package/thread.js
