### ISSUE TITLE
Show the latest version number and repo link above the fold

### ISSUE THREAD

**Issue by achingbrain** [npm/newww#532]
The old website used to have the latest version number and repo link above the fold on all screen sizes.  The new website puts it right at the bottom of the page on small screens and browser windows.

Obviously I'm not the only user, but when I use the npm website, it's either to see what the latest version of a package is, or to try and select between the 15 near-identical packages that do whatever it is I need - i.e. check if the version number is >= 1.0, release frequency, then follow a link to GitHub to look at things like open issues, commit frequency, etc.

The new site puts the README front and centre, but I can read that on GitHub.  The release information is only on npm's website (or at least, so it seems to me), so please don't hide it away.

**Comment by zeke** [comment]
> The release information is only on npm's website (or at least, so it seems to me), so please don't hide it away.

This is great feedback. We're working on improving the "desktop" view to maintain the sidebar even at narrower screen widths. As for the positioning of the stats on the mobile app, it's kind of a tradeoff. We could truncate the readme and add a "show the whole readme" link like GitHub does, but from what I gather people generally dislike that GitHub feature, me included. :)

**Comment by achingbrain** [comment]
Have you considered keeping secondary information (maintainers, stats, dependencies, keywords, dependents) in the sidebar and then moving the version/frequency/repo out?  They are pretty useful.

As for mobile, tabs maybe?  Scrolling through long READMEs to reach the information usually in the sidebar on mobile is pretty tedious.

**Comment by achingbrain** [comment]
This is now much better!
