### ISSUE TITLE
Outdated security settings for npmjs.com SSL cert 

### ISSUE THREAD

**Issue by Krinkle** [npm/newww#538]
As of Google Chrome 42, npmjs.com's certificate type is no longer considered secure. For now, Chrome's counter measure is to merely remove the green badge and let the site through normally. However, assuming the gradual deprecation process continues, future versions will treat it as invalid. That would make it behave the same as for other invalid certificates (e.g. self-signed, expired, or wrong domain) with a warning overlay.

<img width="442" src="https://cloud.githubusercontent.com/assets/156867/5726757/b387c5a2-9b12-11e4-95cd-e8963c4c51a9.png"/>

----

<img width="303" src="https://cloud.githubusercontent.com/assets/156867/5726758/b4b353e2-9b12-11e4-95ff-a8590db44621.png"/>

**Comment by zeke** [comment]
cc @seldo the certmaster

**Comment by seldo** [comment]
We are talking to our certificate provider about how to avoid this becoming a problem before Chrome 42 goes GA (current release is 40, with 41 in beta, so we have some time).

**Comment by zeke** [comment]
@seldo what's the latest on this?

**Comment by seldo** [comment]
Chrome 42 went GA but this change did not go out:

![screenshot 2015-04-23 10 41 21](https://cloud.githubusercontent.com/assets/185893/7303407/53ce11ca-e9a5-11e4-9b12-31204abddccc.png)

I guess they decided it would cause too many false positives, which is what it seemed like.

Closing; we'll reopen if this becomes an issue in future.
