### ISSUE TITLE
Show alternative packages

### ISSUE THREAD

**Issue by tjconcept** [npm/newww#542]
I constantly find myself searching for similar packages to weigh them against each other. This seems to be the next "hurdle" to solve after getting the extreme modularity that npm has finally given the world - you need to quickly asses the available packages in some space of functionality.

I find that currently the older packages are heavily favored because the main ways of finding packages are through search and download stats. That's not necessarily bad things, but it would be really awesome, if once I've found a module covering my needs, I could get a list of alternatives, either linked by one of the authors or somehow selected democratically.

I've published packages because I didn't find some of my taste only to discover later on, that it actually was there, it just wasn't as popular.

In the ideal world the authors themselves would point to alternatives thereby creating an expanding tree.

My hope is that something like this would lead to a little less packages, but more pull requests and reuse of tried code.

Am I nuts?

**Comment by blikenoother** [comment]
yes, there should be list of other similar packages so that we can compare and use relevant package according to specific use case

**Comment by zeke** [comment]
> older packages are heavily favored because the main ways of finding packages are through search and download stats.

This is true. We're hoping that user [collections](https://github.com/npm/newww/issues/313) will make it easier for all npm users to become curators. This is not on our immediate priority list, but it's definitely on our roadmap for 2015.

Closing this issue because there's no immediately actionable problem, but thanks for opening it.

**Comment by tjconcept** [comment]
I do not think collections are a fix here.

The point is that you, as a package author, has extended knowledge about the field and (hopefully) the "competing" packages. The package author is really the best to list alternatives and maybe even outline the differences.

A user collection will be the exact opposite of this. It will contain packages only of a certain style, and they all adhere to the same search-evaluate-bias of the creating user.
