### ISSUE TITLE
"User last published" sidebar line height borked

### ISSUE THREAD

**Issue by zeke** [npm/newww#550]
On mobile chrome, that is.

**Comment by elmasse** [comment]
I'm experiencing this issue in the following browsers and OS:

iOS 8.1.3 Safari Mobile
OS X 10.10.2 Safari

![screen shot 2015-01-27 at 9 39 23 pm](https://cloud.githubusercontent.com/assets/223235/5931482/237e53ce-a67d-11e4-914e-0b7b02a980c2.png)

**Comment by zeke** [comment]
Landed in https://github.com/npm/newww/pull/831

**Comment by elmasse** [comment]
Thank you so much @zeke! It feels good now to open npm site in Safari :+1:

**Comment by zeke** [comment]
:cake:
