### ISSUE TITLE
404 on JSONStream

### ISSUE THREAD

**Issue by faiq** [npm/newww#556]
I was trying to find the JSONStream package on the website and it showed up in the search results, BUT when I clicked it I got a 404. 

![screen shot 2015-01-19 at 5 16 34 pm](https://cloud.githubusercontent.com/assets/5673456/5808804/7baf61ac-9fff-11e4-9e03-f4f4fce7839e.png)
![screen shot 2015-01-19 at 5 19 08 pm](https://cloud.githubusercontent.com/assets/5673456/5808805/8396a344-9fff-11e4-8eb8-a7514bee5937.png)

**Comment by KenanY** [comment]
https://github.com/npm/newww/issues/499?

**Comment by faiq** [comment]
CLOSING BECAUSE I AM STUPID AND APPARENTLY ITS resolved
