### ISSUE TITLE
Similar description should side with one in readme and not the package.json.

### ISSUE THREAD

**Issue by jdalton** [npm/newww#567]
Currently if the description in the readme is similar to the one in the package.json the site hides the one in the readme. This throws a wrench in Lo-Dash packages as the readme description contains links to related content that the json description does not.

Since they are seen as similar it would be better if they sided with keeping the readme description and hiding the json one so that things like links will show up.

See [facets/registry/presenters/package.js](https://github.com/npm/newww/blob/6e5e97d568d30298f424345089fd6f6e78b14ab7/facets/registry/presenters/package.js#L353-L369).

Related to #523. \cc @zeke

**Comment by jdalton** [comment]
Related to #523.

**Comment by jdalton** [comment]
\cc @zeke

**Comment by jdalton** [comment]
This would also remove the need to [special case](https://github.com/npm/newww/blob/6e5e97d568d30298f424345089fd6f6e78b14ab7/facets/registry/presenters/package.js#L354) the `lodash` package.

**Comment by zeke** [comment]
Noted. Will fix when time permits.

**Comment by jdalton** [comment]
Rock! In the meantime I went with the less is more approach. Refocusing the readmes, removing extraneous info, and keeping the titles short. I also used your [simularity](https://www.npmjs.com/package/similarity) package to ensure titles won't be seen a superfluous.

**Comment by zeke** [comment]
Nice. Thanks for working around it.

Not sure if this is something you need, but the site will soon support markdown in `package.description`: https://github.com/npm/marky-markdown/blob/538de5a8ea124cb9d1c9332b9b4ddeefc4b30818/test/index.js#L615-L618

**Comment by zeke** [comment]
@jdalton we just shipped new readme stuff. Special cases are removed, so lodash looks a little funny again: https://www.npmjs.com/package/lodash

**Comment by jdalton** [comment]
Ah ok so no more `similarity` checks and superfluous class? How is the detection for duplicate title names being done?

**Comment by zeke** [comment]
https://github.com/npm/marky-markdown/blob/9e973cf64bec48f0d0f385f3de4fc982ea3b527c/lib/packagize.js

**Comment by zeke** [comment]
`similarity` is still used. `superflous` was vague and offensive, so it's out. Replaced by `badge`, `package-name-redundant`, and `package-description-redundant`.

**Comment by jdalton** [comment]
I had high hopes when clicking the marky-markdown readme that I'd be greeted with an awesome image and some good vibrations. My heart sank when realizing non was to be found.

**Comment by zeke** [comment]
patches welcome!

**Comment by jdalton** [comment]
>  Special cases are removed, so lodash looks a little funny again

That's ok. We'll have a [new readme](https://github.com/lodash/lodash/blob/3.0.0-npm/README.md) in a couple days.

> patches welcome!

I just might ;)
