### ISSUE TITLE
section titles in docs should be hyperlinked

### ISSUE THREAD

**Issue by sam-github** [npm/newww#569]
Its is impossible to refer via a link to specific documentation at the moment. For example, to point to bundledDependencies I need to send a link to https://docs.npmjs.com/files/package.json, and tell people to "search for bundledDependencies", the heading should be a link.

**Comment by anaran** [comment]
https://docs.npmjs.com/files/package.json#bundleddependencies
works for me

**Comment by zeke** [comment]
As @anaran pointed out, there is in fact an id that you can link to, but you have to go digging in the source for it, or guessing it.

One fine day we'll finish integrating [marky-markdown](https://www.npmjs.com/package/marky-markdown) into www and docs, and all headings will automatically be converted to deep hyperlinks.

**Comment by sam-github** [comment]
Ok, thanks for the work around @anaran.

@zeke Yes, a better markdown converter would be fabulous. Btw, I think this is a regression from the old site, which listed all the properties of the package.json on the side tab, and you could click on them, and link to them.

**Comment by zeke** [comment]
We shipped fragment-hyperlinked headings on www today. Example: https://staging.npmjs.com/package/newww#tests

We hope to ship this feature on the docs site soon too.

**Comment by sam-github** [comment]
Great, thanks!
