### ISSUE TITLE
npm install overflow (css)

### ISSUE THREAD

**Issue by funerr** [npm/newww#575]
So I just published a new package named: `dependency-list`
The problem is, that in the site the `t` of `list` is hidden when looking at the `npm install ...` widget.
Is this fixable in npmjs.org's case?

Source: https://www.npmjs.com/package/dependency-list

**Comment by zeke** [comment]
Yeah it's a little annoying, isn't it?

A proposed workaround that would solve the problem for this case specifically is mentioned here: https://github.com/npm/newww/issues/337

Functionally, however, it's not such a problem. The command text is inside an unstyled text input with an event handler that autoselects the entire string on click. So: single-click, copy, you're good to go.

It might also help to have a transparent-white to opaque-white gradient on the right edge of the input, so the overflowing text would fade out in a way that more clearly indicates there's more text. We could also set `overflow` to `visible` on hover...

**Comment by funerr** [comment]
@zeke , what about `text-overflow` (css) ? 
I liked the fading overflow idea.

**Comment by anaran** [comment]
Using :active should be valuable for touch devices, since :hover does not work there (I have not looked at the code yet).
