### ISSUE TITLE
catjs package returns an error

### ISSUE THREAD

**Issue by lastboy** [npm/newww#578]
When trying to load "catjs" npm it returns an error: {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

**Comment by lastboy** [comment]
https://www.npmjs.com/package/catjs

**Comment by lastboy** [comment]
Resolved

**Comment by zeke** [comment]
Thanks for following up @lastboy. :)

**Comment by lastboy** [comment]
No prob, thanx the fix
