### ISSUE TITLE
markdown doc display error

### ISSUE THREAD

**Issue by limingv5** [npm/newww#579]
My NPM module:
https://www.npmjs.org/package/essi

There are some commentaries (just like ) in the README.md, which need to be the original-look. But npm website remove these commentaries, which puzzles me!

**Comment by dimw** [comment]
I can confirm that the used markdown parser seems to strip (required) comments within the HTML code block. Proof: https://www.npmjs.com/package/gulp-inject vs. https://github.com/klei/gulp-inject.

**Comment by psalaets** [comment]
See npm/marky-markdown#14
