### ISSUE TITLE
Error 500 with npmjs.com/package/library

### ISSUE THREAD

**Issue by trusktr** [npm/newww#591]
https://www.npmjs.com/package/library

**Comment by zeke** [comment]
Good catch. It's because `homepage` is not a fully-qualified URL. See http://registry.npmjs.org/library

```
    TypeError: Uncaught error: Cannot call method 'match' of null
  at presentPackage (/Users/z/n/newww/facets/registry/presenters/package.js:67:58)
  at /Users/z/n/newww/facets/registry/show-package.js:72:7
  at /Users/z/n/newww/node_modules/async/lib/async.js:592:17
  at done (/Users/z/n/newww/node_modules/async/lib/async.js:135:19)
  at /Users/z/n/newww/node_modules/async/lib/async.js:32:16
  at /Users/z/n/newww/node_modules/async/lib/async.js:589:21
  at /Users/z/n/newww/facets/registry/show-package.js:119:5
  at /Users/z/n/newww/node_modules/hoek/lib/index.js:791:22
  at process._tickDomainCallback (node.js:463:13)
```

**Comment by trusktr** [comment]
Interesting. I think the expected behavior here (much like with a browser address bar) is that entering a URL without http:// would work, and I think that'd be a nicer solution. Or at least, without any parsing, just put the value in the page, even if it's not a valid link (or not a link at all).

**Comment by zeke** [comment]
I agree that entering a URL without http:// should work. I'm guessing https://github.com/npm/normalize-package-data/issues is the best place for that to be fixed.
