### ISSUE TITLE
Shading on <pre> blocks is as wide as viewport, not as wide as text

### ISSUE THREAD

**Issue by smikes** [npm/newww#593]
Sorry for the terminology in the title, I'm not sure what all the names should be.  Example is https://www.npmjs.com/package/npm-kludge-search, scroll down to "Build a Database" and scroll text horizontally

![shading-limit](https://cloud.githubusercontent.com/assets/5124609/5943649/0701c288-a6de-11e4-843e-beab8f63c6f0.png)

**Comment by zeke** [comment]
@smikes are you still seeing this? If so, what's your OS and browser? Thanks.

**Comment by smikes** [comment]
No, I am **not** seeing this anymore, so might have been a transient display bug.

for the record, OSX Yosemite, Chrome v40.
