### ISSUE TITLE
whitelist of used IP addresses for registry.npmjs.org?

### ISSUE THREAD

**Issue by qwkhyena** [npm/newww#598]
Hey, looked around on npmjs.org's website and couldn't find an official whitelist webpage. Anyone have a list of their current ip addresses? Our network security guys need to add them to an ACL.

So far I've got:
199.27.76.162
23.235.46.162
23.235.39.162

**Comment by qwkhyena** [comment]
Okay, did some more digging and npmjs is using Fastly's CDN. Can't seem to find their whitelist of ip addresses either after a 5 minute Google search. Is this where we should start looking at an internal npmjs repo service and drink the npm-E Kool-aid?

**Comment by seldo** [comment]
Fastly's IP ranges change periodically and are not secret but nor are they public. Here's the current set:

```
{
  "addresses": [
    "23.235.32.0\/20",
    "43.249.72.0\/22",
    "103.244.50.0\/24",
    "103.245.222.0\/23",
    "103.245.224.0\/24",
    "104.156.80.0\/20",
    "185.31.16.0\/22",
    "199.27.72.0\/21",
    "202.21.128.0\/24",
    "203.57.145.0\/24"
  ]
}
```

**Comment by JobaDiniz** [comment]
+1
Is this still the same?

**Comment by ehsalazar** [comment]
@JobaDiniz Updated slightly, with a couple of new ones.
```
{
  "addresses": [
    "23.235.32.0/20",
    "43.249.72.0/22",
    "103.244.50.0/24",
    "103.245.222.0/23",
    "103.245.224.0/24",
    "104.156.80.0/20",
    "157.52.64.0/18",
    "172.111.64.0/18",
    "185.31.16.0/22",
    "199.27.72.0/21",
    "202.21.128.0/24",
    "203.57.145.0/24"
  ]
}
```

**Comment by klien54** [comment]
+1
Is this still the same?
Our network security also needs ip/port for the whitelist.

**Comment by collinforrester** [comment]
I wonder if these were recently updated.  I have the rules @ehsalazar entered applied, but within the last week it's been intermittent.

**Comment by aredridel** [comment]
If you need help with npm services, contacting support@npmjs.com is your best path.
