### ISSUE TITLE
Browsing a keyword

### ISSUE THREAD

**Issue by funerr** [npm/newww#599]
When I click on a tag for a package, lets say: 'dependency'  
I get inconsistent results with regards to searching the keyword.  
Try it out:  
https://www.npmjs.com/browse/keyword/dependency  
https://www.npmjs.com/search?q=dependency

Shouldn't they show the same results?   

I've added pictures for future sake.  
Search:  
![search](https://cloud.githubusercontent.com/assets/1269911/5963030/4a20fc6e-a7f1-11e4-8bf5-5ac4944829f2.png)
Browse:  
![browse](https://cloud.githubusercontent.com/assets/1269911/5963009/166dec4c-a7f1-11e4-9956-abe2cfe0b99b.png)

**Comment by linclark** [comment]
I actually just ran into the same question myself, but then figured out it was my own misunderstanding.

When you go to the keyword page, it only looks for results that have that word in the keywords field of package.json. 

For example:
```
keywords: ["dependency"]
```

The search page looks for the word in multiple fields.
