### ISSUE TITLE
Markdown header parsing partially broken

### ISSUE THREAD

**Issue by silverwind** [npm/newww#600]
Looks like the headings here aren't rendered correctly, as compared to GitHub:

https://www.npmjs.com/package/tcpie
https://github.com/silverwind/tcpie

**Comment by silverwind** [comment]
Looks at least *some* headings do work, I assume the cause is the missing space (`## Heading` vs `##Heading`).

**Comment by zeke** [comment]
From the [commonmark spec](http://spec.commonmark.org/0.17/):

> The opening sequence of # characters cannot be followed directly by a non-space character.

https://github.com/silverwind/tcpie/pull/11

**Comment by silverwind** [comment]
Thanks for clarifying. Apparently Github's markdown flavour relaxes that requirement.

**Comment by zeke** [comment]
Yeah they apparently have a few special cases like that. I makes them seem like more relaxed folk, but for the time being I want to see if we can get away with conforming to the spec.

**Comment by silverwind** [comment]
:+1: standards is the way to go.

**Comment by inikulin** [comment]
Hi guys,

I would like cite Ralph Waldo Emerson here:
 > A foolish consistency is the hobgoblin of little minds, adored by little statesmen and philosophers and divines

I know that standards became a silver bullet in the eyes of many developers after the "dark ages" of the web. However, in this particular case forsing usage of the new CommonMark standard just ended up with broken readmes in npm without any particular pros. How should package maintaners act? Publish new versions of their packages to support npm's markdown? I find it wrong on many levels. While most packages are hosted on GitHub why we need this inconsistency with the GitHub's markdown?

**Comment by zeke** [comment]
@inikulin point taken. We're not rigid about compliance to the CommonMark spec. If we end up seeing lots of readmes with a common syntactic deviation from the spec, we'll happily add exceptions to [marky-markdown](https://www.npmjs.com/package/marky-markdown)
