### ISSUE TITLE
package page not reliably rendering `#` markdown syntax

### ISSUE THREAD

**Issue by 75lb** [npm/newww#604]
if you see this page:
https://www.npmjs.com/package/handbrake-js

the markdown headings, e.g. `#handbrake-js `, `##Installation`,  `###System Requirements` etc have not rendered as html headings.. this particular README looks fine on Github.. is there something wrong with my markdown, or is this a markdown parser issue?

**Comment by bcoe** [comment]
hey @75lb, we're using a parser now that adheres to the [CommonMark spec](http://spec.commonmark.org/0.17/#atx-headers), which indicates:

  # characters cannot be followed directly by a non-space character

If you toss a space in after those headers, e.g., `## Installation`, it should fix the parsing issue.

**Comment by 75lb** [comment]
ok, will do thanks
