### ISSUE TITLE
markdown unexpectedly rendering an <object> element

### ISSUE THREAD

**Issue by 75lb** [npm/newww#606]
this markdown (correctly escaped)
`## a.pick(arrayOfObjects, ...property) ⇒ <code>Array.&lt;object&gt;</code>`

is generating this html (notice the unwanted `<object>`!)
`<h2><a>a.pick(arrayOfObjects, ...property) &#x21D2; Array.<object></object></a></h2>`

which markdown generator do you use? I need to test my markdown renders correctly before publishing to npm..

**Comment by zeke** [comment]
http://npm.im/marky-markdown is our new markdown thing, which uses https://www.npmjs.com/package/markdown-it under the hood.

What is the name of your package?

**Comment by 75lb** [comment]
hi zeke, thanks - i will test against these parsers.. the package i referred to is here: https://www.npmjs.com/package/array-tools (sorry, i should have provided this info to begin with .. )

**Comment by zeke** [comment]
Hi @75lb. Is this still an issue?

**Comment by 75lb** [comment]
nope, looks like you fixed it.. cheers!
