### ISSUE TITLE
npm weekly sign up has cors issue

### ISSUE THREAD

**Issue by RichardLitt** [npm/newww#610]
To reproduce:
 - Go to https://www.npmjs.com/npm-weekly
 - Put in your email.
 - Select 'subscribe to weekly'
 - Push.

There was no response upon submit, either successful or not, for me. The console gave this error: 

> Refused to load the script 'about:blank' because it violates the following Content Security Policy directive: "script-src 'self' https://www.google-analytics.com https://fonts.googleapis.com https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js https://s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js https://npmjs.us9.list-manage.com https://js.hsforms.net/ https://forms.hubspot.com/ https://js.hs-analytics.net".

Screenshot:
![screen shot 2015-02-02 at 6 17 47 pm](https://cloud.githubusercontent.com/assets/910753/6013338/11d042e2-ab08-11e4-85ef-302e745299f2.png)

Chrome Version 41.0.2272.35 beta (64-bit); Mac OSX; Ghostery, Disconnect, AdBlocker enabled.

**Comment by linclark** [comment]
I believe this was fixed in master... @zeke, has there been a deploy of newww since then?

**Comment by linclark** [comment]
Actually, I just tested this in Chrome and it worked for me. It didn't before we made the fix last week. hmmm....

**Comment by RichardLitt** [comment]
Worked in an incognito window. Not sure what's up with that. :/

**Comment by linclark** [comment]
Thanks for reporting this. I'm guessing it was some kind of caching issue or something. Going to close this, if anyone else runs into this bug please open another issue.

**Comment by RichardLitt** [comment]
Still happening. Weird. But yeah, if no one else has it...

**Comment by fvdm** [comment]
I'm have this problem too, but _only_ on this page: https://www.npmjs.com/package/foscam
Tested with Safari, Chrome and Firefox.

![schermafbeelding 2015-05-04 om 16 44 25](https://cloud.githubusercontent.com/assets/93784/7455477/df64e3b4-f27c-11e4-81b3-f025c6267151.png)

The white section should display the readme and you can see other JS bits like author and license are not loaded.

Safari:

```
[Error] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'
  https://forms.hubspot.com/uploads/form/v2/419727/9a2b4ac5-ef09-43e6-854a-d82c92347c9d https://forms.hubspot.com/uploads/form/v2/419727/6672f0d7-d2df-4696-a164-a8fa139d8f15 https://forms.hubspot.com/uploads/form/v2/419727/64c6e95b-b2c7-4989-a8ae-d967645e5198 https://forms.hubspot.com/uploads/form/v2/419727/d9ba17d5-606e-456d-a703-733c67f5e708 https://js.hsforms.net/forms/current.js https://api.hubapi.com https://internal.hubapi.com https://js.hs-analytics.net https://api.stripe.com https://checkout.stripe.com/checkout.js https://js.stripe.com https://platform.twitter.com/oct.js https://www.google-analytics.com https://fonts.googleapis.com https://s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js https://npmjs.us9.list-manage.com https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js".
(foscam, line 0)
```

Chrome:

```
vendor.min.js:1
GET https://www.google-analytics.com/analytics.js
net::ERR_BLOCKED_BY_CLIENT
  (anonymous function) @ vendor.min.js:1
  (anonymous function) @ vendor.min.js:1
```
```
vendor.min.js:2
GET https://js.hs-analytics.net/analytics/1430750100000/419727.js
net::ERR_BLOCKED_BY_CLIENT
  (anonymous function) @ vendor.min.js:2
  (anonymous function) @ vendor.min.js:2
```
```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
  https://js.hs-analytics.net/analytics/1430750100000/419727.js
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
  https://js.hs-analytics.net/analytics/1430750100000/419727.js
```
