### ISSUE TITLE
Vagrant vm is missing g++

### ISSUE THREAD

**Issue by gtanner** [npm/newww#611]
In attempting to start up a new local dev environment the call to:

```
npm install
```

fails with a native build error

Running:
```
sudo apt-get install g++
```

in the VM and rerunning ```npm install``` will now work.

**Comment by chentsulin** [comment]
Encountered the same issue today.

**Comment by zeke** [comment]
We are in the process of phasing out the development VM, in favor of a staging environment with a fully replicated registry, a redis, etc that will be accessible to the public. We're also refactoring the test suite to not rely on locally-running services like elasticsearch, redis, couch, etc. This will allow public users to get up and running with the newww codebase more easily.

All of this work is happening in the r2 branch. Follow along at https://github.com/npm/newww/pull/325
