### ISSUE TITLE
Structured metadata for better search results

### ISSUE THREAD

**Issue by seldo** [npm/newww#625]
Looking at our site in Google's Structured Data Testing Tool it appears Google has trouble interpreting our site as a content site and is instead interpreting it as a search engine:

http://www.google.com/webmasters/tools/richsnippets

We can probably rectify this by adding metadata that declares package pages as "products" and giving them explicit descriptions, etc.

**Comment by linclark** [comment]
This was actually what my thesis was on, and I've already reached out to their team about possibly including us as one of the sources for the SoftwareApplication Rich Snippet type, so I could take this on.
