### ISSUE TITLE
Password restrictions in browser do not match command line

### ISSUE THREAD

**Issue by saibotsivad** [npm/newww#643]
I just had to reset my password, so I reset it via the web interface.

Being a good internet citizen, I used a nice local random character generator, and included one of these: `!:@`

However, when I go to login via the command line `npm login`, it informs me thusly:

    npm WARN Password passwords cannot contain these characters: '!:@" 

If these restrictions are enforced on the command line, they should also be enforced on the web interface.

**Comment by othiym23** [comment]
I agree that the two should match, but in this case it's a mismatch in versions. You don't say what version of npm you're running, but newer versions (at least all of `npm@2`) no longer has these restrictions on what passwords can contain. Update npm (`npm install -g npm`) and you should be set.
