### ISSUE TITLE
undefined in README

### ISSUE THREAD

**Issue by jcblw** [npm/newww#651]
small issue. 

When having the word undefined in a comment of a `README.md` file on the NPM js site the word undefined never shows up.

This is github
![screenshot from 2015-02-17 23 45 13](https://cloud.githubusercontent.com/assets/578259/6243851/1a053a6e-b6ff-11e4-89c6-d48b1669a8d1.png)

This is the results on NPM
![screenshot from 2015-02-17 23 45 24](https://cloud.githubusercontent.com/assets/578259/6243862/384c6d4e-b6ff-11e4-9ad2-c158a5c08605.png)

**Comment by zeke** [comment]
Thanks for reporting, @jcblw. This may be resolved when we ship a new version of marky-markdown with this fix: https://github.com/npm/marky-markdown/pull/27

**Comment by zeke** [comment]
This fix will land when we ship newww's `r2` branch, which has a newer version of marky-markdown (5) with the updated `sanitize-html` dependency: https://github.com/npm/marky-markdown/releases
