### ISSUE TITLE
package descriptions don't escape HTML

### ISSUE THREAD

**Issue by tim-evans** [npm/newww#663]
This is a potential XSS vulnerability. I caught this by using a custom HTML tag in the name of my package.

**Comment by zeke** [comment]
What package are you referring to?

**Comment by tim-evans** [comment]
It was https://www.npmjs.com/package/ember-document-title, but I removed that because it was causing problems with the README.

**Comment by zeke** [comment]
Can you point me to a git commit with the offending markup?

**Comment by tim-evans** [comment]
https://github.com/paddle8/ember-document-title/commit/427307fe78710974403e045174b2147e893f0ce7

**Comment by mmalecki** [comment]
@tim-evans thanks for reporting this! We've verified that it's impossible to perform an XSS like that - our markdown parser strips all the tags that are not whitelisted (@zeke tells me that our whitelist is `"div","h1","h2","img","meta","pre","span","iframe"`) and all the attributes (like `onclick`).

**Comment by zeke** [comment]
Specifically: https://github.com/npm/marky-markdown/blob/ff3ed7caf99814d3392c5a54589d38d2511e8484/test/index.js#L380-L400
