### ISSUE TITLE
Glitchy display of unpublished packages

### ISSUE THREAD

**Issue by jhermsmeier** [npm/newww#667]
![screen shot 2015-02-23 at 19 09 27](https://cloud.githubusercontent.com/assets/244907/6333721/b56988f4-bb8f-11e4-9e19-217f3a611f16.png)

**Comment by zeke** [comment]
This has been fixed in the r2 branch and will be fixed when we ship it. Thanks for reporting!

https://github.com/npm/newww/pull/325
