### ISSUE TITLE
Alternatives to Gravatar

### ISSUE THREAD

**Issue by d4nyll** [npm/newww#678]
I guess this comes down to personal preference but I get the sense that a lot of the users do not want to use Gravatar to host their avatar. I did not have an account and was 'forced' into creating one so I can customize my profile picture. Some arguments against Gravatar are:

1. It 'forces' people to have a Wordpress account (which 1. reminds me of PHP and 2. also having to manage another account)
2. You cannot delete your account
3. Commercial service
4. Some people in China can't access it because of the [GFW](http://en.wikipedia.org/wiki/Great_Firewall)
5. Users might not want to link their existing Gravatar to npm (see 1.)

#433 suggests using the GitHub avatar, whilst npm/npm#6851 suggests simply providing a URL linking to your desire avatar.

However, reasons why it cannot be implemented right now:

1. Using URL means storing/copying or caching the images ourselves (Takes work. This might change with npm's [own CDN](https://github.com/npm/newww/issues/291#issuecomment-65163254), which might come with support for package icons.)
2. Integrating with other CDN also takes work, with no obvious advantages

Alternatives:

1. [avatars.io](http://avatars.io/)

**Comment by d4nyll** [comment]
Closing this issue as it's more of a converging point / issue from different repos

**Comment by Siilwyn** [comment]
Any chance of this being opened again?
I have no avatar on NPM because of the needed Wordpress account.
