### ISSUE TITLE
Are the stats aggregated case insensitively?

### ISSUE THREAD

**Issue by seangarner** [npm/newww#707]
Whilst looking for a jsonpath implementation I noticed that the download stats for 2 modules were identical which given the numbers involved seemed unlikely.

https://www.npmjs.com/package/jsonpath
https://www.npmjs.com/package/JSONPath

Note that both have the same package name but the latter has caps, which makes me wonder if the stats are pulled with names being case insensitive leading to the stats for both of these packages to be inaccurate.

**Comment by zeke** [comment]
Good catch! This should probably be filed at https://github.com/npm/download-counts/issues/new

cc @seldo

**Comment by mmalecki** [comment]
I'm going to close this one as we're tracking this in npm/download-counts#13, thanks for reporting Sean!
