### ISSUE TITLE
Use validate property of route config for defining input validation

### ISSUE THREAD

**Issue by mtharrison** [npm/newww#712]
Is there any reason the schemas for payloads are defined inline in the handlers rather than in the route configurations?

Happy to contribute a PR if anyone thinks it's worth doing this the 'hapi way'?

**Comment by zeke** [comment]
Hey @mtharrison wanna send a baby PR to illustrate the concept?

**Comment by mtharrison** [comment]
I've issued a PR with an example. A few notes:

- I've had to add `request.logger` in a new `onRequest` extension point so it's available during validation
- I've stuck the validation config inline in the routes file but they might be better living in their own module
- I've split the handler in the example into 2 (one for GET and one for POST) because the validation is applied to the handler no matter which method is used (because all fields are optional I probably didn't need to do this actually)
