### ISSUE TITLE
Broken links in Dependents and Dependencies

### ISSUE THREAD

**Issue by petey** [npm/newww#729]
See modules like npm that have lots of dependents/ dependencies: https://www.npmjs.com/package/npm

After 50 dependencies it outputs `[object Object]` with a link to `https://www.npmjs.com/package/[object%20Object]`

After 20 dependents, it outputs `and 404 more` with a link to `https://www.npmjs.com/package/and%20404%20more` 

These are clearly incorrect.

**Comment by pjbr** [comment]
This is an error at https://github.com/npm/newww/blob/master/templates/registry/package-page.hbs#L153 The scope of the name variable makes it so you can't just use href='/browse/depended/{{name}}'

**Comment by fundon** [comment]
I saw same issue.

`https://www.npmjs.com/package/and%20404%20more`
