### ISSUE TITLE
Use SVG Icons

### ISSUE THREAD

**Issue by jenius** [npm/newww#73]
SVGs are wonderful -- resolution-independent, easily scalable, and very light. I noticed the preview site is still using non-retina pngs, would you guys consider switching to using SVGs instead?

**Comment by zeke** [comment]
We've had a few SVG-related PRs since this issue was opened: https://github.com/npm/newww/pulls?utf8=%E2%9C%93&q=is%3Apr+svg+

I'm going to close this, noting that we will happily accept more SVG-related PRs in the future. :)
