### ISSUE TITLE
Irrelevant search results

### ISSUE THREAD

**Issue by danecando** [npm/newww#739]
I've had a package up on npm for a few months called 'hapi-sequelized'. In the package.json file it has the keywords 'hapi' and 'sequelize'. When searching 'hapi sequelize' we come up 4 pages back and most of the results before us aren't relevant to the search query. 

I was told to open an issue about this if there's anything more I can do to help please let me know.

**Comment by KenanY** [comment]
https://github.com/npm/newww/issues/335

**Comment by zeke** [comment]
As @KenanY implied, #335 is where we are consolidating all the search feedback until we have time to focus on search. Please provide input there if it's not already represented by the existing comments. Thanks!
