### ISSUE TITLE
"and x more" links under dependents are targeting the wrong thing

### ISSUE THREAD

**Issue by othiym23** [npm/newww#751]
1. visit <https://www.npmjs.com/package/validator>
2. click "and 431 more" at the end of the displayed Dependents list
3. get sent to <https://www.npmjs.com/package/and%20431%20more> instead of the full list of dependents

**Comment by ivanph** [comment]
Duplicate of #729. Submitted a fix on #740

**Comment by othiym23** [comment]
Closing in favor of #729 / #740.
