### ISSUE TITLE
Responsive breakpoints are not very generous to slightly smaller than normal screens

### ISSUE THREAD

**Issue by domenic** [npm/newww#756]
Examples on my Surface Pro 2:

Gigantic profile picture

![screenshot 28](https://cloud.githubusercontent.com/assets/617481/6745587/75a08a6c-cefc-11e4-9850-6340f19a5fce.png)

No sidebar, I have to scroll all the way to the bottom to find the current version

![screenshot 29](https://cloud.githubusercontent.com/assets/617481/6745599/b1fb6568-cefc-11e4-9c5f-f39db9f719b9.png)

In my case `document.body.clientWidth` is 884 and I still seem to be getting dropped down to phone layout or something?

**Comment by zeke** [comment]
We rolled out a fix for this last week. The breakpoint changed from `1170px`-ish to `760px`-ish
