### ISSUE TITLE
Markdown heading rendered incorrectly

### ISSUE THREAD

**Issue by afanasy** [npm/newww#774]
https://www.npmjs.com/package/db3
Heading ##Disconnected should be rendered as heading, now its showing as plain text (look at corresponding github page for correct rendering: https://github.com/afanasy/db3)

**Comment by KenanY** [comment]
Duplicate of https://github.com/npm/newww/issues/600, https://github.com/npm/newww/issues/604. Markdown is parsed as CommonMark, which [states](http://spec.commonmark.org/0.18/#atx-headers):

> The opening sequence of `#` characters cannot be followed directly by a [non-space character](http://spec.commonmark.org/0.18/#non-space-character).

**Comment by afanasy** [comment]
Thanks!
