### ISSUE TITLE
https://docs.npmjs.com/files/.npmignore "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by Krinkle** [npm/newww#808]
https://docs.npmjs.com/files/.npmignore

> RangeError: Maximum call stack size exceeded

**Comment by KenanY** [comment]
Weird. Happens with any page starting with a `.`

  - https://docs.npmjs.com/files/.dot
  - https://docs.npmjs.com/.dot

**Comment by KenanY** [comment]
Also I only see this on docs.npmjs.com so might be an issue for [`npm/docs.npmjs.com`](https://github.com/npm/docs.npmjs.com)

**Comment by zeke** [comment]
Yep. Moving it over to https://github.com/npm/docs/issues/135

Thanks for reporting, @Krinkle
