### ISSUE TITLE
Github source link does not direct offsite

### ISSUE THREAD

**Issue by perfetti** [npm/newww#840]
The source link for projects seems to be relative to npmjs.com and does not redirect to http://github.com/{project_link}

**Comment by perfetti** [comment]
![npm issue](https://cloud.githubusercontent.com/assets/3189653/7051138/ff9f5dbe-ddf3-11e4-9f39-5e40f5eb9933.png)

**Comment by zeke** [comment]
Thanks for reporting, @perfetti.

Tracking here: https://github.com/npm/normalize-package-data/issues/59 and I opened a PR to fix the package.json in the interim: https://github.com/hgoebl/mobile-detect.js/pull/25
