### ISSUE TITLE
Non-package 404's display full URL

### ISSUE THREAD

**Issue by mmalecki** [npm/newww#865]
For example, if you visit the access page for a package that does not exist, full URL will show up in the 404 message.

**Comment by zeke** [comment]
@mmalecki are you suggesting that we not display the URL in the page? I guess it's not that helpful, as you have it right there in your location bar...

![screen shot 2015-04-14 at 9 43 16 am](https://cloud.githubusercontent.com/assets/2289/7142101/c1cc0528-e28a-11e4-908d-9a4991eb2176.png)
