### ISSUE TITLE
503 backend read error

### ISSUE THREAD

**Issue by btmdave** [npm/newww#890]
Just got this error after a few attempts that didn't resolve:

Error 503 backend read error

backend read error

Guru Mediation:

Details: cache-iad2136-IAD 1429109318 3487436242

Varnish cache server

**Comment by zeke** [comment]
Hey @btmdave thanks for reporting. This was a brief blip of downtime, but I wanted to make sure we got it up on our status page before closing the issue: http://status.npmjs.org/

**Comment by timrwood** [comment]
@zeke, I've been getting these errors intermittently over the last few weeks in Chicagoland.

```
Error 503 backend read error
backend read error
Guru Mediation:
Details: cache-ord1728-ORD 1447957213 1242562005
Varnish cache server
```
