### ISSUE TITLE
THEAD elements display none

### ISSUE THREAD

**Issue by numtel** [npm/newww#895]
Readmes with tables that include heading columns have their heading columns hidden due to a CSS rule:

```
table thead {
  display: none;
}
```

This makes tables very confusing.

Example: https://www.npmjs.com/package/pg-live-select

**Comment by zeke** [comment]
Good catch, @numtel. Feel free to submit a PR if we don't get to this quickly enough.

**Comment by numtel** [comment]
That should take care of it I think. Still kind of confusing not having any table cell borders, want me to come up with a PR for that? Being cautious as I don't want to get in a case of causing regressions somewhere.
