### ISSUE TITLE
Package `gaze` has reverted to showing a very old version

### ISSUE THREAD

**Issue by orrc** [npm/newww#900]
In October 2014 I included [gaze][0] `0.6.4` in my `package.json`.  
Today, a colleague tried to run `npm install`, but it failed as the registry currently claims that `0.5.1` is the newest version.

But `0.5.1` was released in [February 2014][1], and the package page and GitHub both show the changelog which indicate the latest version is `0.6.4`, as released in [April 2014][2].

So why has the npm website, between October and now, reverted to showing a (much) older version as the newest?

-
(Sorry if this is the wrong place to report this; I couldn't see a better way to report errors of this nature on the website.)

[0]:https://www.npmjs.com/package/gaze
[1]:https://github.com/shama/gaze/commit/dad5345
[2]:https://github.com/shama/gaze/commit/de8f5e2

**Comment by KenanY** [comment]
@orrc `0.5.1` is [tagged](https://docs.npmjs.com/cli/dist-tag) as `latest`, hence the site is correct in saying that "0.5.1 is the latest of 26 releases". Relevant issue which shows that this is intentional by `gaze`'s author: https://github.com/shama/gaze/issues/178

**Comment by orrc** [comment]
@KenanY Ah ha! Thanks for the details.
