### ISSUE TITLE
Invalidate cache after package publish event

### ISSUE THREAD

**Issue by zeke** [npm/newww#902]
When a new package version is published, that package should be removed from the catch so its author can immediately view the newly published version on the website.

**Comment by fvdm** [comment]
Is this actually working?

I published an update to my package (1.8.0) but the website is still displaying the old version (1.7.3) even after clearing my browser cache. Normally it takes a couple of minutes for updates to appear.

https://www.npmjs.com/package/geoip2ws

The CLI returns the correct data:

```sh
npm info geoip2ws version time.modified
version = '1.8.0'
time.modified = '2016-03-18T21:40:04.281Z'
```
