### ISSUE TITLE
Create weighted rating using GitHub

### ISSUE THREAD

**Issue by brennanMKE** [npm/newww#943]
If accounts are linked with GitHub it would be possible to create a weighted rating based on a GitHub user's total number of stars across all of their repos with Node source code. If indutny rates a project at 5 I would definitely value that rating over someone who has no popular GitHub repos. Perhaps the weighted rating could be used to display the top 20 modules by category by this weight rating to help select useful modules for security, networking, social, etc.

**Comment by aredridel** [comment]
This gets into some really difficult issues around what evidence there is for a package to be the correct one, and stars have some major positive and negative factors there, and stars in github have particular positive feedback loops that make them a less useful signal compared to others. I'm going to close this issue but know your feedback has been heard and we'll take it as input in deciding how to improve our search ranking.
