### ISSUE TITLE
Add GitHub login option to website

### ISSUE THREAD

**Issue by brennanMKE** [npm/newww#945]
I am logged into GitHub on my home and work computer but I only have my password for the npm website stored on my keychain on my home computer. I would like to simply log in using GitHub. Developer services like Parse have this option which is very helpful.

Having users connected to their GitHub identity enables many useful features.

**Comment by fvdm** [comment]
+1 This could be just as smooth as with Travis CI and others: to login only hit the login button.

**Comment by brennanMKE** [comment]
Here are some docs.

https://developer.github.com/guides/basics-of-authentication/

**Comment by fassetar** [comment]
+1

**Comment by jden** [comment]
:+1: pleeeeease

**Comment by aredridel** [comment]
This is widely requested but actually difficult as we do not actually privilege github over other source control services. There are lots of security issues as well and it complicates things significantly. Know you've been heard and we may come up with ways that mitigate some of these things, but I'm going to close this issue as this decision will come from our product design some time in the future.
