### ISSUE TITLE
License display is not fully flexible for the forms the input takes

### ISSUE THREAD

**Issue by 1j01** [npm/newww#949]
"none" isn't exactly a license, now is it?
I'd suggest "no license specified" or "no specified license" for the phrasing (or "**n**o **p**ermit **m**entioned" :dancers:)
[Here's the relevant template code,](https://github.com/npm/newww/blob/13e26e0eaf5c6699f068bb5418d932af76be4aef/templates/package/show.hbs#L81-L86) except I'm not sure why the template receives `license.name = "none"` instead of `license` being `null`-y.

**Comment by aredridel** [comment]
The license you want to use in this case is `UNLICENSED`.

**Comment by 1j01** [comment]
This is a grammar error in the template code and it is not fixed.

**Comment by aredridel** [comment]
This is fixed by #996, thank you @kemitchell !
