### ISSUE TITLE
running locally

### ISSUE THREAD

**Issue by rutaihwa** [npm/newww#959]
When i try to to get the site running locally i get these issues
![npm_install](https://cloud.githubusercontent.com/assets/481028/7492393/6036a98a-f400-11e4-99d1-fc0b012413f1.png)
![run_dev](https://cloud.githubusercontent.com/assets/481028/7492394/6052b418-f400-11e4-9530-033d36450428.png)

**Comment by rutaihwa** [comment]
:(

**Comment by aredridel** [comment]
highlights should install -- this sounds like the install didn't complete. Which version of npm are you running?

**Comment by rutaihwa** [comment]
It seems its okay now, with a bit of `npm clear cache` magic and updating the node, finally I can run it locally. Thanks.
