### ISSUE TITLE
Error: getaddrinfo ENOTFOUND alerts.sinfini.com

### ISSUE THREAD

**Issue by issacbalaji** [npm/newww#962]
{ [Error: getaddrinfo ENOTFOUND alerts.sinfini.com]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'alerts.sinfini.com' }

my code is 

var request = require('request');
request(url, function (error, response, body) {
  if (!error && response.statusCode == 200) {
    console.log(body) // Show the HTML for the Google homepage. 
  }else{
      console.log(error);
  }
});

**Comment by KenanY** [comment]
@issacbalaji How is this issue relevant to this repository?

**Comment by KenanY** [comment]
@issacbalaji ping?

**Comment by aredridel** [comment]
no response, issue with `request` module use, not the npm website. Closing.
