### ISSUE TITLE
Package profile remains despite being unpublished.

### ISSUE THREAD

**Issue by ehsalazar** [npm/newww#972]
A package tombstone remains at https://www.npmjs.com/package/tollbooth-client despite `anpm unpublish tollbooth-client -f`.

**Comment by koresar** [comment]
Good day guys,

Any progress on that?

We really would love to see this tombstone removed from other people's sight.

**Comment by ehsalazar** [comment]
We've receive another user support ticket with the same behavior. The user ran `npm --force unpublish v0.0.1` and I attempted an `anpm unpublish -f proto-log`. Running `npm view proto-log` returns `404 'proto-log' is not in the npm registry.`

- The package url remains up but displays an error state. https://www.npmjs.com/package/proto-log
- The package remains listed on the user's profile page. https://www.npmjs.com/~thejsj

**Comment by koresar** [comment]
This remind me that I was doing `npm --force unpublish` too (without a specific version, just the entire module).

**Comment by thefabulousdev** [comment]
Happened the same thing with me. 
https://www.npmjs.com/package/container.js

**Comment by koresar** [comment]
I consider this as resolved. Consider closing this issue @ehsalazar 
Cheers.

**Comment by ehsalazar** [comment]
@koresar thanks for the reminder. it's happened a couple more times with other users but appears to be a registry issue and not newww. cheers.
