### ISSUE TITLE
Unrelated repo URL from package.json

### ISSUE THREAD

**Issue by ppvg** [npm/newww#978]
I've noticed some packages include an unrelated repo URL in their `package.json`.
For example, [mysql-on-the-rocks](https://www.npmjs.com/package/mysql-on-the-rocks) lists [npm/npm](https://github.com/npm/npm) as its repository.

This causes the package page to list the unrelated repo:

> ![image](https://cloud.githubusercontent.com/assets/67802/7640397/5167a1b4-fa83-11e4-9ad6-024ee87df9d2.png)

...and its stats:

> ![image](https://cloud.githubusercontent.com/assets/67802/7640404/59c15490-fa83-11e4-9c9b-8a62877a1230.png)

**Comment by KenanY** [comment]
@ppvg For whatever reason, that's literally what that module's author has as the repository:

https://github.com/olivierkaisin/node-mysql-on-the-rocks/blob/029e7e9a7fab6779ef2e1609f3c9bd42691eefae/package.json#L22-25

**Comment by ppvg** [comment]
@KenanY Yes, it's probably a case of [copy-paste-forget](https://docs.npmjs.com/files/package.json#repository). Still, it could be confusing or misguiding, especially if the mismatch is more subtle. It would be nice if npm www could check the repo's package.json to see if it matches the published name. Don't know how feasible this is, though.

In the meantime: olivierkaisin/node-mysql-on-the-rocks#1. Thanks for pointing me to the correct repo.
