### ISSUE TITLE
Install package returns 404

### ISSUE THREAD

**Issue by fvdm** [npm/newww#984]
I just published an update for my package and it is available in the web UI. With `npm info searchitunes gitHead` I get the correct hash, but when I do `npm install searchitunes` I get a 404.

```
$ npm install searchitunes
npm ERR! fetch failed https://registry.npmjs.org/searchitunes/-/searchitunes-2.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

Other installations with fine, it's only this one.
[Package page](https://www.npmjs.com/package/searchitunes)

**Comment by fvdm** [comment]
I think something may have gone wrong with auto deployment to npm from Travis CI. I just updated the package without auto deploy and it did work, but took a while to complete and npm said it couldn't read the JSON.

There is still a problem somewhere, but at least my package can be downloaded again.

**Comment by aredridel** [comment]
This is a registry problem and likely transient; feel free to raise such issues with npm support
