### ISSUE TITLE
Link directly to a module's license file

### ISSUE THREAD

**Issue by scottgonzalez** [npm/newww#985]
Following up from https://github.com/npm/npm/issues/4473#issuecomment-103703124.

If a module has a LICENSE (or similar) file, the license link should point to that file instead of opensource.org.

**Comment by aredridel** [comment]
For that, you can specify a license as `see license in LICENSE` or similar SPDX expression. Otherwise we will.

**Comment by scottgonzalez** [comment]
Not really. Text that tells the user to go find the license file themselves is pretty far from a link in the license field that actually takes the user to the license. This would ultimately destroy the utility of listing a license if the license isn't actually shown on the page (you'd just see `see license in LICENSE` instead of `MIT` with a link).

**Comment by scottgonzalez** [comment]
Note that this would also make it impossible to find modules with a filter on licenses since we've now lost the actual license info.
