### ISSUE TITLE
Link to multi license is broken

### ISSUE THREAD

**Issue by SimenB** [npm/newww#992]
For example https://www.npmjs.com/package/JSONStream. Clicking the license 404s, as it tries to open http://opensource.org/licenses/(MIT%20OR%20Apache-2.0). What you'd open in this case I have no idea. Provide 2 links perhaps?

Also, the text is `(MIT OR Apache-2.0) license`, which isn't very human readable.

**Comment by SimenB** [comment]
Pinging @kemitchell as requested in https://github.com/npm/normalize-license-data/issues/1 :smile:

**Comment by kemitchell** [comment]
As much to remind myself as anything else:

- [ ] `spdx.parse(json)` for AST to translate to links and `<span>`s
- [ ] link to spdx.org/licenses/$identifier, not OSI

**Comment by kemitchell** [comment]
Ongoing work in [spdx-to-html.js](https://github.com/kemitchell/spdx-to-html.js).

**Comment by Krinkle** [comment]
Affecting https://www.npmjs.com/package/jshint. Currently renders a 404 Not Found to <http://opensource.org/licenses/(MIT%20AND%20JSON)>.

Change is https://github.com/jshint/jshint/commit/e47168f5aa.

**Comment by aredridel** [comment]
We'll have to parse the expression with the spdx library and link more carefully. Thank you for the issue!

**Comment by aredridel** [comment]
This is fixed by #996, thank you @kemitchell !
