### ISSUE TITLE
Package page reads wrong readme file

### ISSUE THREAD

**Issue by greduan** [npm/newww#995]
As you can see in the following images, the right header is being loaded, but the wrong readme file. I went to the project's GitHub page to show the content of the right readme.

![2015-05-21-195154_1280x800_scrot](https://cloud.githubusercontent.com/assets/2314074/7762008/7e0ee66c-fff3-11e4-82d9-a418e75a5632.png)
![2015-05-21-195214_1280x800_scrot](https://cloud.githubusercontent.com/assets/2314074/7762009/7e27df5a-fff3-11e4-8a61-b8ee9f1099cc.png)

**Comment by soldair** [comment]
thanks for pointing this out. this  module is fixed and im writing a scrip that should find any others. =)

**Comment by greduan** [comment]
Nice. :)

Yeah after I reported this I founnd some more examples but I was too lazy to report them. Thanks for fixing. :)
