### ISSUE TITLE
Package non-github homepage links to repository

### ISSUE THREAD

**Issue by slaskis** [npm/newww#999]
[A package](https://www.npmjs.com/package/object-ready) I just published links the homepage to the repository url which gives a 404.

But if I run `npm home` in the terminal it does it right so I'm pretty sure my [package.json](https://git.department.se/department/object-ready/raw/master/package.json) is correct.

I couldn't quickly figure out why this is from looking at the source code (presenter looks right to me) otherwise I'd gladly help out with a PR but just wanted to give you a heads up.  Cheers!

**Comment by icyflame** [comment]
@slaskis Removing the `.git` from the end of the repository URL fixed the problem, Is there anything wrong with doing that?

**Comment by slaskis** [comment]
Then it wouldn't be git clone-able since it would point to the website and not the repository. And I'm pretty sure that's the purpose of that attribute.

**Comment by icyflame** [comment]
Yes, I have gone through the official package.json spec. It says that the value of this field should be such that it can directly be passed to VCS. :+1:

**Comment by aredridel** [comment]
This should no longer be an issue since we read package.json with some normalization now. Feel free to open a new issue if it's still happening for you.

**Comment by slaskis** [comment]
Thanks!
